### ISSUE TITLE
glTF2Exporter includes materials used by excluded meshes.

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Babylon.js#10009]
See:
https://forum.babylonjs.com/t/can-gltf-export-a-specific-mesh-from-scene/10641/3

Repro:
https://www.babylonjs-playground.com/#YBEKDT#4

Expected result:
Fan materials and textures should not be included in exported glTF from this playground.

**Comment by sikandar66** [comment]
I used file compressor for my website  [latest choices](https://www.latestchoices.com) thank you

**Comment by daoshengmu** [comment]
Hi @sebavan and @Drigax, I have a local fix to exclude unused materials when exporting a gltf file. But, I am aware another issue in glTFExporter.ts that is regarding to the mesh's sideOrientation. Maybe I can file another issue to follow it up.

Per [glTFExporter.ts#L1586]( https://github.com/daoshengmu/Babylon.js/blob/master/serializers/src/glTF/2.0/glTFExporter.ts#L1586), I notice due to `(sideOrientation == Material.ClockWiseSideOrientation && convertToRightHandedSystem && bufferMesh.overrideMaterialSideOrientation !== bufferMesh.material?.sideOrientation)` is *true*, it makes the index data of primitives be reorder when exporting. On the other hand, It looks like `gltfLoader.ts` doesn't do any reorder in indices, we only make this reorder in `glTFExporter.ts`. So, when importing the exported gltf data, we will see the vertex winding is wrong.

IIUC, gltf file should be right-handed coordinate system according to its spec. In https://www.babylonjs-playground.com/#YBEKDT#4 demo, we are using left-handed. It supposes to reorder the gltf model's index data while loading, but we didn't. So, I am wondering if we choose _counterclockwise_ frontface instead of _clockwise_ which is supposed to be chosen in left-handed system backface culling.

**Comment by bghgary** [comment]
The loader compensates for handedness change with a root transform with a negative scale. Loaders need to be as fast as possible, so updating the winding order of indices on load is not an option.

**Comment by sebavan** [comment]
Thanks a lot Gary I completely missed the ping somehow... @daoshengmu sorry for the delay

**Comment by daoshengmu** [comment]
> The loader compensates for handedness change with a root transform with a negative scale. Loaders need to be as fast as possible, so updating the winding order of indices on load is not an option.

I agree updating the winding order of indices on load is too slow. It looks like we did something wrong with [_convertToRightHandedSystemMap](https://github.com/daoshengmu/Babylon.js/blob/master/serializers/src/glTF/2.0/glTFExporter.ts#L1680) that is for a root transform with a negative scale.
