### ISSUE TITLE
[XR] WebXR support a different coordinate system for hand joints than Oculus

### ISSUE THREAD

**Issue by rickfromwork** [BabylonJS/Babylon.js#10139]
The set of hand joints used on Oculus have their X and Z coordinated facing a different direction than the set of hand joints that WebXR provides. While Oculus uses X to point to hte base of the hand, WebXR uses Z to point to the hand's base. This means that actions that are dependent on the joint orientations will only work in one scenario or the other. For example, the hand meshes on Oculus (probably) look fine, but look completely distorted when using a HoloLens.

For reference, here are the coordinate systems used:
WebXR (image is OpenXR's implementation, the only difference is that OpenXR has the addition of a palm joint):
![image](https://user-images.githubusercontent.com/70608380/113629513-5ccaa580-961b-11eb-85bd-51126fec9f3d.png)
Oculus:
![image](https://user-images.githubusercontent.com/70608380/113629527-60f6c300-961b-11eb-8759-7c86dc51e0e1.png)

Babylon.js should be normalizing the joint orientations so that all sources provide the same set of axis.

**Comment by RaananW** [comment]
Oh, wow.

I totally agree with what yo uare saying, but how would you be able to know what orientation the hand object is at?

This feels like a lack of standard on the devices themselves, and not something we can account for. Unless I am missing something?

BTW - Where did you get the information regarding WebXR axis data? This might be something the oculus team have overlooked!

**Comment by rickfromwork** [comment]
> Oh, wow.
> 
> I totally agree with what yo uare saying, but how would you be able to know what orientation the hand object is at?

I had placed PositionGizmo objects on each joint in the playground scene [here](https://www.babylonjs-playground.com/#F41V6N#360) to test with.

> This feels like a lack of standard on the devices themselves, and not something we can account for. Unless I am missing something?

Yeah, I talked more with the webXR team after creating this issue, and they decided to push back against Oculus for not following the specs. So Babylon.JS will likely just need to update the hand mesh to the webXR specs instead of Oculus specs, and then the new mesh can even be used to help push Oculus to correct their behaviour.

> BTW - Where did you get the information regarding WebXR axis data? This might be something the oculus team have overlooked!

I had to ask the WebXR team myself too, so I don't doubt it could have been overlooked. They don't have any visuals, but they do mention [here](https://immersive-web.github.io/webxr-hand-input/#xrjointspace-interface) that the joint "has its -Y direction pointing perpendicular to the skin, outwards from the palm, and -Z direction pointing along their associated bone, away from the wrist."

**Comment by PatrickRyanMS** [comment]
Oculus has changed their mapping in the latest Browser update on the Quest (so I am assuming across all their devices as well). I am currently reworking and testing out an updated rig.

**Comment by PatrickRyanMS** [comment]
Mapping the orientation of the joints in the skeleton to the image above seems to correct the issue so long as the root joint of the skeleton is aligned to the default orientation of the DCC tool. The root joint remains at the world origin so does not follow the same orientation as the rest of the joints in the skeleton. In the image below, the root joint has the same orientation as the Maya scene (which can be seen in the small indicator at the bottom left) while the rest of the joints in the skeleton have the orientation shown by the gizmo of the selected joint.

![image](https://user-images.githubusercontent.com/31326855/115076677-c1a2bd00-9eb1-11eb-8a6d-f2f931a42690.png)

This is the test mesh I am using to determine if the joint orientation is correct. This image is just the static glb loaded in the sandbox to show the correct orientation of the cubes in the mesh:
![image](https://user-images.githubusercontent.com/31326855/115076631-b0f24700-9eb1-11eb-80b9-84eca55cd2c7.png)

This is a video capture in the Quest showing the right hand as broken since the last update to Browser that I took on Wednesday. The left hand is using the refined joint orientation to match the XR spec now.

https://user-images.githubusercontent.com/31326855/115077257-95d40700-9eb2-11eb-8aae-694727b01d62.mp4

**Comment by PatrickRyanMS** [comment]
Reworked joint orientation with regards to mesh for correct deformation. There was a bunch of tweaking on the rotation of the joints in the skeleton to get the mesh skinned correctly to the tracked joints. To make this easier in the future, I changed the UVs on the mesh slightly to allow for correct export/import of skinning weights. This will require a slight change in the shader for the Babylon.js hands. Once that tweak is made, I create the right hand mesh and PR.

![image](https://user-images.githubusercontent.com/31326855/115323838-a946d280-a13d-11eb-91b7-d0948179b5cb.png)

**Comment by PatrickRyanMS** [comment]
Tweaked shader and translated to the right hand model. Joints needed to be reoriented after mirror since mirroring the skeleton in a DCC tool will not retail the same the exact same joint orientation as shown above. Needed to manually reorient each joint to retain a +Z toward the previous joint "up the hierarchy" (in quotes since there is no traditional joint hierarchy since all joints are siblings under the root joint).

![image](https://user-images.githubusercontent.com/31326855/115476596-0bafd980-a1f7-11eb-893e-984de971715d.png)

**Comment by syntheticmagus** [comment]
Fixed by @PatrickRyanMS and @RaananW.
