### ISSUE TITLE
Slider3D starts swallowing all clicks mid-interaction if dragged off of with another mesh behind it

### ISSUE THREAD

**Issue by rickfromwork** [BabylonJS/Babylon.js#10478]
This is possible with a simple setup of just a ground mesh and a Slider3D control.
https://www.babylonjs-playground.com/#IFDI9M

If you click and drag the slider, it is possible to drag it in a way that it stops responding to input while dragging. The bar will appear to stutter, and if you let go of the slider while it is doing this (mouse button release), the release will be dropped. This means the slider will continue to respond to the mouse movement, and the mouse cannot be used for things like moving the camera around until the slider receives a pointer up event (by pressing and releasing on it).

https://user-images.githubusercontent.com/70608380/121432742-e8202a00-c92f-11eb-88ca-fc97b605d3f2.mp4

**Comment by RaananW** [comment]
Nice catch :-) 
This happens because the event listener is on the slider's box and not on the screen. So the minute you move the mouse faster than the box's movements, or out of the box's boundaries, the mouse events stop affecting the box. Moving the mouse slowly with the box works (but obviously not the solution here).
Without digging to much in the code, it seems like the minute a mouse-down is triggered on the box, we should listen to all pointermove events, and not only to those who hit the box.

**Comment by rickfromwork** [comment]
Resolved with #10547
