### ISSUE TITLE
Add a sampler Node to let user share samplers

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#11095]
- [x] Create a new SamplerBlock
- [ ] Add a new optional input to TextureBlock

Discussion: https://forum.babylonjs.com/t/nme-sample-one-texture-with-multiple-uvs-in-one-pass/23875/5

**Comment by Popov72** [comment]
Do you mean "sampler" as a synonym for "texture"? **Sampler** for me would mean an object with the uWrap, vWrap, samplingMode, etc properties which is not what we need I think(?)

I think this block would be more something like "InternalTextureBlock" (or maybe "ImageBlock" as in Blender). If connected to the `Texture` block, the texture of the `Texture` block (if defined) would not be used but the one from the `Image` block would be used instead.

**Comment by deltakosh** [comment]
I mean sampler as the way to avoid the mix with the TextureBlock

ImageBlock works as well. The idea is to extract the sampler info out of the TextureBlock (so we can share samplers ultimately)

**Comment by deltakosh** [comment]
And btw, the texture is the host to all the uvwrap and samplingMode so for me it makes sense to call it sampler :)

But from a user perspective ImageSourceBlock could be better

**Comment by Popov72** [comment]
I asked because it is a bit confusing with the WebGPU terminology, where **sampler** is the object that holds the uWrap, vWrap, samplingMode, etc properties and is separate from the **texture** object. When doing a lookup, you need a **texture** + a **sampler** + uv coordinates to get the value of a texel. But in the WebGL world **sampler** means texture+sampler properties wrapped up into the same object (cf. the `sampler2D` type in shader code).

**Comment by deltakosh** [comment]
ok makes sense! I will use ImageSourceBlock then

**Comment by sebavan** [comment]
Closed by #11096

**Comment by sebavan** [comment]
Sampler block add in #11096 11096
