### ISSUE TITLE
why Using HTTP Range Requests and what is major impact w/o or with using

### ISSUE THREAD

**Issue by sannysoni123** [BabylonJS/Babylon.js#11254]
i am using to load glb with SceneLoader.Append but not sure regarding 

>  SceneLoader.OnPluginActivatedObservable.addOnce(function (loader) {
            if (loader.name === "gltf") {
                loader['useRangeRequests'] = true;
            }
        });

majorly use for one request makes different partition requests with use of useRangeRequests but why need to make partition and why this feature use to implement..
https://doc.babylonjs.com/divingDeeper/importers/progressiveglTFLoad
Document what’s being loaded after the glb, I notice the UI progress take an additional chuck of time after the glb has been downloaded. What’s it doing? so please describe on this that would be very helpful... thanks

**Comment by sebavan** [comment]
Github is only used for validated issues or feature requests from the forum where I can see you already asked :-) https://forum.babylonjs.com/t/why-using-http-range-requests-and-what-is-major-impact-w-o-or-with-using-it/24500

You ll find the answer there but for anybody else, it basically helps processing the file we load during their download.

e.g. if you load 50Mb, instead of waiting for all of it to be downloaded before parsing, we can start in parallel decreasing the load time latency.
