### ISSUE TITLE
mesh.lookAt incorrect in left handed scene when enabling world space flag 

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#11423]
When using mesh.lookAt in a left handed scene and enabling the flag for world space in the last argument, the orientation of a mesh brought in through glTF is incorrect. In this image the icon should be above the barrel, but with a left handed system importing a glTF and enabling the world space flag on mesh.lookAt rotates the mesh 180 degrees on local Z:

![image](https://user-images.githubusercontent.com/31326855/141033951-47e9b876-434f-49dd-9789-1400a19113ce.png)

If the scene is set to right handed, mesh.lookAt renders correctly with the world space flag set:

![image](https://user-images.githubusercontent.com/31326855/141033807-4513018d-58cd-40de-ad11-f7843f619cf9.png)

Logging this issue now and will come back with a repro.

**Comment by sebavan** [comment]
@PatrickRyanMS, let us know when you ll have a repro for this one so that we can address it ASAP

**Comment by PatrickRyanMS** [comment]
@sebavan, here is the repro for it: https://playground.babylonjs.com/#G1SVUJ

If you comment line 5 to use a left handed scene, you will see the icon will rotate below the ground. Setting the lookAt parameter to world space is what is causing the need for the right handed system. The camera is imported in the glb with animations on the camera parent baked into the glb.

**Comment by sebavan** [comment]
Thanks a lot !!!

Adding @Popov72 to the thread as he worked on smthg pretty close recently on the forum

**Comment by Popov72** [comment]
I don't think there's something to fix here:

When calling `meshes.prop_pickup_icon.lookAt(new BABYLON.Vector3(meshes.dolly.position.x, 0.4, meshes.dolly.position.z), 0, 0, 0, BABYLON.Space.WORLD);` you want the icon to look at `(meshes.dolly.position.x, 0.4, meshes.dolly.position.z)`, but this point is in local space, not world space: it is a point local to the dolly space. As `meshes.prop_pickup_icon` is itself in the same hierarchy than meshes.dolly, you can pass `BABYLON.Space.LOCAL` instead of `BABYLON.Space.WORLD` and it will work as expected.

It's also possible to use a world position for the `lookAt` method if you put `meshes.prop_pickup_icon` outside the hiearchy:
```javascript
meshes.prop_pickup_icon.parent = null;
...
scene.registerBeforeRender(() => {
    const pos = meshes.dolly.getAbsolutePosition();
    meshes.prop_pickup_icon.lookAt(pos, 0, 0, 0, BABYLON.Space.WORLD);
});
```
