### ISSUE TITLE
[NME] Preview window icons scaled to wrong size

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#11490]
The three icons on the top of the preview panel - play, background color, and pop out - are scaled too large. The icons on the bottom of the panel are the correct scale for reference. 

![image](https://user-images.githubusercontent.com/31326855/142518507-1dcc9c0f-7049-4e8f-a2c9-9d1cff7b69f4.png)

**Comment by deltakosh** [comment]
I have added our 2 experts (I believe there maybe a leak between GUI editor and NME editor)

**Comment by msDestiny14** [comment]
![image](https://user-images.githubusercontent.com/67929198/142564801-7c1ebd0b-6dda-49c6-b37f-3aaab52da7dd.png)

How does this look? I made these changes on my branch can put out a PR if this looks correct. I changed the css of the icons to 24px instead of 40px. 

Not sure what the memory leak is? Or if its related.

**Comment by carolhmj** [comment]
I think what @deltakosh meant by leak was some CSS from the GUI editor that reflected into the NME?

**Comment by msDestiny14** [comment]
Ah. There is a second one in GUI editor as well. Let's delete that. :)

**Comment by deltakosh** [comment]
Yes I believe this is a CSS leak with GUI editor
