### ISSUE TITLE
Investigation for rounding _getGlobalViewport for GUI

### ISSUE THREAD

**Issue by msDestiny14** [BabylonJS/Babylon.js#11539]
Investigate if this Is this something we really need or not? Will it cause rounding errors later on in code?
In Babylon coordinates we are allowing floats but is this proper for JS and HTML?

**Comment by deltakosh** [comment]
Can you elaborate a bit more?

**Comment by ecoinomist** [comment]
Yes, in 3D world `Floats` are normal, but for canvas width/height it is expected integer, because many frontend libraries, packages and CSS `@media` queries rely on those numbers to switch layout and achieve pixel perfect rendering.

Example css media query:
```
@media screen and (min-width: 768px) {
      // apply layout for non-mobile users
  }
```  
now if for some reason, the width is not exactly `768`, but `767.999999997897`, then CSS fails to switch to non-mobile layout.

Another case is when css applies `width`, it uses up to 6 decimals for precision, which may end up with visible artifacts.

**Comment by deltakosh** [comment]
ok I see and what is your proposal?  I mean wanna do a PR?

**Comment by ecoinomist** [comment]
sry for late reply, I don't check github very often.
My reply was related to comment about rounding width and height for this:
https://github.com/BabylonJS/Babylon.js/pull/11528/files/b66a83f775be776c08f52aa2c439a40b91a78621#diff-b7386cd4ef5afe8b5f28af0308b28016617189caba5c49a9cb70a07c9c8d3985

Can make a PR if you think that is OK

**Comment by deltakosh** [comment]
Please do :)

**Comment by darraghjburke** [comment]
Can we close this issue? @ecoinomist

**Comment by ecoinomist** [comment]
> Can we close this issue? @ecoinomist

Yes, of course, I do not have permission o close.
