### ISSUE TITLE
Direct registration of materialplugin doesn't work

### ISSUE THREAD

**Issue by brunobg** [BabylonJS/Babylon.js#11651]
**Repro**
- Bug repro on https://playground.babylonjs.com/#22HT5Z#1
- Expected result: Second sphere should be black and white because material plugin is running on it
- Current result: Nothing happens

**Additional context**
I thought materialPlugins could be registered to individual materials directly, but the PG doesn't work. even with `sphere2Material.markDirty();` the material plugin isn't applied. Am I missing something?

**Comment by Popov72** [comment]
You need to enable the plugin by calling this._enable(true): by default the plugins are disabled.

Also, you should always associate a define with your plugin because the list of defines (and their values) is what triggers a recompilation of the shader: a shader is recompiled only if a value of a define changes.

Here the effect for the first sphere is created/compiled when the sphere is rendered, then when the second sphere must be rendered the same effect is reused because the list of its defines+values is exactly the same than for the first sphere. Here's a fixed PG:

https://playground.babylonjs.com/#22HT5Z#3

**Comment by sebavan** [comment]
Still weird that without enabling it and if there is only one material it would apply ???

**Comment by Popov72** [comment]
That will be fixed by #11654

**Comment by brunobg** [comment]
Thanks @Popov72, I'll update the docs with the information from your comment.

**Comment by brunobg** [comment]
> You need to enable the plugin by calling this._enable(true): by default the plugins are disabled.

Note that https://playground.babylonjs.com/#GC63G5#1 is enabled even without it.
