### ISSUE TITLE
Draco decoding bug in Sandbox for GLB files

### ISSUE THREAD

**Issue by Aloalo** [BabylonJS/Babylon.js#11685]
Four assets are attached:
- **no_draco_float_uvs.glb** - No draco compression, float UVs
- **draco_float_uvs.glb** - Draco compression, float UVs
- **no_draco_ushort_uvs.glb** - No draco compression, normalized unisigned short UVs
- **draco_ushort_uvs.glb** - Draco compression, normalized unisigned short UVs (**problem asset**)

While draco and the UV format vary, everything else in these assets is identical.
The asset which has draco applied to normalized unsigned short UVs doesn't render correctly in Sandbox, as if all UVs are (0, 0) (see screenshots). The problem asset renders correctly in three.js based viewers, Khronos' sample viewer and blender.

**Screenshots**

![no_draco](https://user-images.githubusercontent.com/2706313/146981676-b8b53a61-e85e-4b95-8c58-1ef34367dff5.png)
![draco](https://user-images.githubusercontent.com/2706313/146981679-54337862-5b0c-4e70-81a0-6d8dd7aec7ab.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome 96.0.4664.110

**Additional context**

Files to repro with:
[test.zip](https://github.com/BabylonJS/Babylon.js/files/7757387/test.zip)

**Comment by sebavan** [comment]
Thanks for the repro !!! @Popov72 can you have a look ?

**Comment by Popov72** [comment]
`draco_float_uvs` is not draco compressed: could you provide a draco compressed file so that I can more easily compare it with `draco_ushort_uvs`?

Thanks in advance.

**Comment by Popov72** [comment]
What is the tool you are using for generating the draco compressed files?

After the uv attribute has been decoded, the `normalized()` method called on this attribute returns `false`, which does not seem right...

It works in other viewers probably because they are reading the `normalized` info from the uv accessor and are doing the appropriate normalization process if it is `true`. I don't know if it is what we are expected to do (I can't see any detail in the spec). 

As an `attribute.normalized()` method exists on the Draco decompression side, I would have thought that for normalized attributes it should return `true`, enabling either the decompressor to normalize the values or let us know it should be normalized without having to read the accessors from the glTF file. This schema would seem to acknowledge the fact we should not need to use the accessors when decompressing a Draco compressed geometry and that everything should be self contained:
https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_draco_mesh_compression/README.md

I could be wrong, thought, I'm no expert in the glTF field. @bghgary would probably know and I think he will have a look when he comes back from vacation.

**Comment by Aloalo** [comment]
I am using [gltf-pipeline](https://github.com/CesiumGS/gltf-pipeline).
