### ISSUE TITLE
Instancing is disabled when scale is 0

### ISSUE THREAD

**Issue by geobalas** [BabylonJS/Babylon.js#11952]
Instancing gets disabled when the scaling is 0, causing a drop in frame rate, confirmed in the forum https://forum.babylonjs.com/t/framerate-drop-on-ios15-with-scaling-0/25928/6.

**Repro**
- The bug is reproduced here https://playground.babylonjs.com/#SM5RNH#24, and it's really visible on webkit browsers where the frame rate suffers the most.
- Expected result: Good frame rate
- Current result: Really low frame rate

**Desktop:**
 - OS: MacOS
 - Browser: Safari
 - Version: Monterey v12.1

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 - OS: iOS 15.1
 - Browser Safari

**Additional context**
The instancing problem had been checked by a dev from the webkit team https://bugs.webkit.org/show_bug.cgi?id=236130

**Comment by deltakosh** [comment]
Ok this is NOT a bug in Babylon but I have a way to workaround the issue in Safari :)
In a nutshell, the instances are desactivated because they do not have the same world matrix determinant as their source. If you simply set the scaling of the skull to 0 it will work

That being said I will try to see if I can add a way to not send the instances AT all when scaling is 0
