### ISSUE TITLE
Change private members in gizmo to protected ones

### ISSUE THREAD

**Issue by braineo** [BabylonJS/Babylon.js#12795]
**Is your feature request related to a problem? Please describe.**

I am trying to customize `AxisDragGizmo` and replace the ones in `PositionGizmo` in TypeScript.

Since `AxisDragGizmo` has a lot `private` not `protected` variables, I needed to copy most of the code of `AxisDragGizmo` instead of extending it.

But `PositionGizmo` only accept `xGizmo` to be instance of `AxisDragGizmo`. Maybe Interface can be defined for each gizmo to make customization easy?

```ts
export class PositionGizmo extends Gizmo {
    /**
     * Internal gizmo used for interactions on the x axis
     */
    public xGizmo: AxisDragGizmo;
```

**Describe the solution you'd like**

It would be nice either having members being protected ones so that developers can subclass gizmo, or having Interfaces for gizmos

**Discussion**
[discussion](https://forum.babylonjs.com/t/expose-interface-for-gizmo/32497)

**Comment by sebavan** [comment]
I would definitely prefer an interface here. Making everything protected won t solve the issue. 

An interface would help keeping a common contract in a cleaner way.

@CedricGuillemet, @RaananW  ?

**Comment by braineo** [comment]
@sebavan probably both are needed

for example in `PositionGizmo`, if xGizmo can accept `IAxisDragGizmo`, that's great. Any class implemented `IAxisDragGizmo` can be assigned.

```
export class PositionGizmo extends Gizmo {
    public xGizmo: IAxisDragGizmo;
```

But it does not change the fact extending `AxisDragGizmo` is hard since there are many private members, including mesh and material. In order to make it look different, developer needs to reimplement it and cannot reuse the existing code.

**Comment by RaananW** [comment]
I agree with both of you - an interface would be a wonderful solution, but as @braineo says - extending the existing class will be hard because of the private members. I am not sure what functionality you are trying to extend/change, but I assume you need access to those:

```javascript
    private _gizmoMesh: Mesh;
    private _coloredMaterial: StandardMaterial;
    private _hoverMaterial: StandardMaterial;
    private _disableMaterial: StandardMaterial;
    private _dragging: boolean = false;
```

I am not opposing to making them protected. as long as they stay within the scope of the class it is fine.

From the way the gizmo is used in PositionGizmo and the way it is implemented (and without diving too much into the code TBH), it feels like an interface to the Gizmo class is missing.

**Comment by braineo** [comment]
Sure, the Interface shouldn't be too hard to add. I can update the PR.
