### ISSUE TITLE
Implement glTF KHR_audio extension

### ISSUE THREAD

**Issue by docEdub** [BabylonJS/Babylon.js#13248]
## Overview

A new glTF audio extension has been proposed at https://github.com/KhronosGroup/glTF/pull/2137 that we are implementing.

Current work is being done on my fork's branch at https://github.com/docEdub/Babylon.js/tree/221027-glTF-audio-extension.

**Comment by bghgary** [comment]
Closing for now. If the audio extension becomes more ready, we can reopen.

**Comment by sebavan** [comment]
cc @bghgary

**Comment by bghgary** [comment]
@aaronfranke You probably already know this, but I am part of the Khronos 3D Formats working group.

I personally like the idea of an audio emitter better than the audio graph one as I have concerns with the audio graph version, but we don't have any stakes in these types of extensions to put much effort/priority into it at the moment. @docEdub is our resident audio guy and he has reviewed/commented on some of the specs. Maybe he can comment more here. Realistically, we can help with the implementation of such an extension and give feedback through the implementation, but since we have no direct usage of these extensions, it will be hard to justify more involvement at the moment.

**Comment by docEdub** [comment]
I'm in the middle of updating our audio engine right now and I'd prefer not to implement this extension with our current engine. We can revisit this when the new engine is further along.

**Comment by docEdub** [comment]
> Hi! Is the new engine further along now? :)

Yes, it is! But there a few more things to do before I can get to this.
