### ISSUE TITLE
instantiateModelsToScene doesn't take parents of clones nodes into account

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#13454]
See https://forum.babylonjs.com/t/proper-way-to-create-an-instance-of-a-loaded-glb/37478/18

**Comment by Popov72** [comment]
I had a quick look and it seems we would need to access the `instanceSourceMap` during the recursive instantiation in the `Mesh` class, but this property pertains to the asset container...

Maybe I'm missing something, but it didn't seem to be an easy fix (or should we pass it to `instantiateHierarchy` instead of passing `newSourcedMesh`?), so I preferred reporting the bug instead of trying to fixi it!

**Comment by RaananW** [comment]
I'm always happy if there is an easy fix :-)
I'll have to investigate and see the entire process and see what is the best way to implement it

**Comment by carolhmj** [comment]
The main problem is here: https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Meshes/mesh.ts#L763, we're assuming that any instanced mesh that is a child of a mesh has that same mesh as its original source, which is not true. I think we'll really need some kind of lookup map, as there is a scenario where we can have at least two different outcomes depending on how the instantiation is done:

Let's say you have a scene with this structure, with two top-level empty meshes (EM1 and EM2). EM1 has two children: mesh M1 and that mesh's instance I1 (importantly, M1 is the source mesh of I1, NOT EM1):
![image](https://user-images.githubusercontent.com/6002144/214552117-59fc266b-75cc-42fa-82b3-bb493c9e786e.png)
And EM2 has also two children, I2 and I3, whose source is also M1

Let's say I call instantiateHierarchy on empty mesh EM2. By the current code, it's going to clone EM2: CEM2 (since it's an empty mesh), and then instantiate I4 and I5 setting CEM2 as its source, which is incorrect! Instead, I'd expect I4 and I5 to be instantiated with M1 still as its source, so the cloned tree would look like this:
![image](https://user-images.githubusercontent.com/6002144/214553648-a33f70d2-1a36-4e54-bca1-57a2e7c425fa.png)

Now, the second scenario would be to instantiateHierarchy on BOTH EM1 and EM2. In this case, the source mesh of all the instances would be getting cloned, which means all the newly created instances would be expected to point to the NEW clone, not the original one:
![image](https://user-images.githubusercontent.com/6002144/214554712-20cd884f-8e0a-4fb5-ad3a-5b34ce8e258e.png)

So we really need to keep track of what's getting cloned and when. And also probably do it in two passes, first meshes then instances. It's def a tricky situation.

**Comment by carolhmj** [comment]
On the AssetContainer, instead of just calling instantiateModelsToScene on each root mesh as it goes, we'll need to build a dependency graph to determine the cloning/instancing order and guarantee that every object already has its dependencies in place on the process.

**Comment by 852Kerfunkle** [comment]
@carolhmj On that dependency graph:

First, a word of warning: I know *very little* about the inner workings of babylonjs. I'm not sure it would be feasible, elegant or practical.

But instead of a full dependency graph, you could walk up the dependency tree for each node to be cloned, and if you encounter a node in the "root set", ie EM1 or EM2, you either clone the dependency, or not.
