### ISSUE TITLE
NME Procedural Texture, Light Projection Texture Issue

### ISSUE THREAD

**Issue by PirateJC** [BabylonJS/Babylon.js#13940]
https://playground.babylonjs.com/#0PJ5IW#7

This playground uses a NME Procedural Texture as a Spotlight projection texture and appears differently on different machines. 

It SHOULD look like this:

![image](https://github.com/BabylonJS/Babylon.js/assets/1668182/5e84b28b-dbda-4a62-b5e9-2ade71430b5c)

Seems like the behavior is inconsistent depending on the machine?

**Comment by Popov72** [comment]
After some testing on my computer (RTX 3080Ti):
* it's ok in WebGPU
* it's ok if I use "OpenGL" as the Angle backend

Also, I can see that if I open the developer tool window on my second monitor and move it around quickly, it impacts the display and makes it flicker / become black randomly...

Because of this last point, I would vote for a driver bug...

**Comment by deltakosh** [comment]
Should we close that bug then?

**Comment by Popov72** [comment]
Have you a pointer on a similar past issue? I can't really understand how it can happen (where to put the abs / clamp?)...

**Comment by sebavan** [comment]
I tried with Spector and not finding anything obvious :-( Let s close and raise it internally to see if the driver could be fixed.

**Comment by deltakosh** [comment]
@sebavan do you mind pinging Chrome team or edge team to confirm?

**Comment by sebavan** [comment]
Yup I did already :-) just waiting on their feedback to update the thread
