### ISSUE TITLE
WebAssembly.Module doesn't parse at byte 325: can't get 0th Type's return value

### ISSUE THREAD

**Issue by zhushunqing** [BabylonJS/Babylon.js#14315]
Not working properly when browsing in Safari

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com): https://playground.babylonjs.com/#R66K4K#1
- Expected result: 
- Current result: Not working properly

**Screenshots**
<img width="1777" alt="image" src="https://github.com/BabylonJS/Babylon.js/assets/1759717/d63170ea-b03d-4228-b060-25e5bf0af9ea">

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.2 (21G320)
 - Browser: Safari Version 
 - Version: 16.2 (17614.3.7.1.7, 17614)

**Additional context**

**Comment by sebavan** [comment]
Can you check with 16.6 of safari ? I think older version were having issues. cc @CedricGuillemet  to confirm.

Also, let s move the discussion to the forum https://forum.babylonjs.com/ until we have a stable repro as the template mentions.

**Comment by CedricGuillemet** [comment]
I can confirm there was this kind of issue with older version of iOS (16.2, 16.3 IIRC)
I've always my mac up to date because of security policy so I can't confirm it on MacOS but the issue looks the same.
No work around except updating Safari. This is on Apple side and they fixed the bug with more recent versions.

**Comment by zhushunqing** [comment]
MacOS 13.5 (22G74)
Safari 16.6 (18615.3.12.11.2)
I confirmed that the upgraded Safari is working fine

**Comment by zhushunqing** [comment]
I also encountered the same problem on some older Android devices. I guess there may be something wrong with the compilation of HavokPhysics.wasm. If I use Ammo.wasm, There is no problems with WebAssembly.

In this example, The test page runs on cordova, The inner webview version of this device is Android Webview 81.0.4044.138, 
We cannot guarantee the user's mobile Webview version, so if possible we hope to maintain compatibility.

<img width="1136" alt="image" src="https://github.com/BabylonJS/Babylon.js/assets/1759717/4c073916-098d-4fac-8b59-829628a97a58">

**Comment by zhushunqing** [comment]
@sebavan @CedricGuillemet Can you please reconfirm this issue? Thanks!

**Comment by CedricGuillemet** [comment]
Do you know what can be the cause for this issue  @eoineoineoin ? 
@zhushunqing how old is this version of the webview? when was it released?

**Comment by zhushunqing** [comment]
Maybe a little later this time @CedricGuillemet 
Chrome 81 (81.0.4044.111) for Android
Wednesday, April 15, 2020

https://chromereleases.googleblog.com/2020/04/chrome-for-android-update_15.html

**Comment by eoineoineoin** [comment]
At that offset in the WASM is a WebAssembly function:

```
(func (param i32) (result v128))
```

Which is the first time a v128 was referenced in the WASM. If the browser is failing to parse that, it indicates it is too old and doesn't have support for SIMD, which we depend on.

**Comment by nyan-left** [comment]
@sebavan 

We recently discovered Havok physics isn't working on older iOS devices (pre-16.4) due to lack of SIMD support. Two forum posts highlight this:

- [Havok loading issue in Safari](https://forum.babylonjs.com/t/havok-cannot-be-loaded-in-any-safari-browser/41481/14?u=nyan-left)
- [WebAssembly error on old iOS](https://forum.babylonjs.com/t/webassembly-error-havok-project-in-old-ios-device-iphone-6s/40213)

While device updates can solve this, it's not always possible. Many users can't or won't update, and we aim to support a wider audience.

Given that Havok's math library doesn't have a non-SIMD version, could we explore creating one? This could improve compatibility without compromising performance on newer hardware.

As an alternative approach, we've also opened an issue with Emscripten:
[Emscripten Issue #22470](https://github.com/emscripten-core/emscripten/issues/22470)

Could we reopen this issue to discuss potential solutions, considering both the non-SIMD math library approach and any insights from the Emscripten team?

**Comment by sebavan** [comment]
let me add @CedricGuillemet  and @eoineoineoin to the thread

**Comment by tangobravo** [comment]
Thanks for considering this! Someone from emscripten kindly mentioned [SIMDe](https://github.com/simd-everywhere/simde) which is a header-only scalar implementation of various SIMD intrinsics instruction sets.

Assuming that's how the Havok implementation is written, it might make it relatively painless to get a working fallback build for wasm runtimes that lack SIMD support. From some [stats](https://telemetrydeck.com/blog/ios-market-share-04-24/) I found from April this year, there were still more than 8% of iOS users running version < 16.4.

**Comment by tangobravo** [comment]
I just had a quick play around in compiler explorer, see here: https://godbolt.org/z/z6nMG7ojP

It seems LLVM's vector extensions also have scalar implementations if your codebase uses any of those. If you're using intrinsics, then it looks like SIMDe should offer a solution to map those to scalar operations. Hopefully that makes it feasible to provide a fallback wasm build without requiring `-msimd128`. There's also [wasm-feature-detect](https://github.com/GoogleChromeLabs/wasm-feature-detect) which can be used to decide which build to load at runtime.
