### ISSUE TITLE
Grease line testing

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/Babylon.js#14835]
Color not taken into accoun (white) for second grease line:

https://playground.babylonjs.com/#5TQ0RZ

Second curve points set is not an array ?

https://playground.babylonjs.com/#5TQ0RZ#1

Is it possible to have a simple lerp `colorDistribution` ?

**Comment by sebavan** [comment]
@RolandCsibrei   can you have a quick look ?

**Comment by RolandCsibrei** [comment]
> Color not taken into accoun (white) for second grease line:

You have to use `colors: colors2` instead of `colors2`. There is no `colors2` property if the 

> Second curve points set is not an array ?

Same issue here:

`{ points: points2 }` instead of just `points2`.

Working one:
https://playground.babylonjs.com/#5TQ0RZ#2



> Is it possible to have a simple lerp `colorDistribution` ?

Sure it is but you can use gradients instead:
https://playground.babylonjs.com/#H1LRZ3#233

Or a better solution is to use your own color texture and set the sampling mode to `TEXTURE_LINEAR_LINEAR`: 
https://playground.babylonjs.com/#H1LRZ3#55

You can find more examples here:
https://doc.babylonjs.com/features/featuresDeepDive/mesh/creation/param/greased_line
