### ISSUE TITLE
wrong position of bounding box

### ISSUE THREAD

**Issue by yedpodtrzitko** [BabylonJS/Babylon.js#15370]
https://forum.babylonjs.com/t/wrong-position-of-bounding-box/51828

(while the forum thread is marked as solved, the solution is just a workaround for my specific use-case, the bug itself is still present)

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#6QTQLT%2315):
- Expected result: clicking the violin attached to bone will show bounding box in correct position
- Current result: violin's bounding box is misplaced

**Screenshots**

![Screenshot 2024-08-07 at 22 34 43](https://github.com/user-attachments/assets/e52be9e4-fe60-4844-a592-1e85000810b1)

**Desktop (please complete the following information):**
 - OS: macOS 14.6
 - Browser Firefox
 - Version 128

**Comment by deltakosh** [comment]
There is no bug. You are picking the root and not the violin itself
Here is a fix: https://playground.babylonjs.com/#6QTQLT#19

The root even if flagged as a mesh has no geometry.

**Comment by deltakosh** [comment]
To be a bit more complete:
- The `getHierarchyBoundingVectors` API return the min and max in world space
- The boundingInfo constructor expects the min and max to be in local space for the given object
- The main problem with your approach is to rebuild a boundingInfo for a specific object out of data outside of its local space
- One solution could be to get the min and max of each child (but in their local space), transform that vectors into world space (this is not what you get out of minimumWorld and maximumWorld because this one are axis aligned before being returned) and then convert these vectors into main object local space to build its bbox

**Comment by deltakosh** [comment]
Example: https://playground.babylonjs.com/#6QTQLT#22

**Comment by yedpodtrzitko** [comment]
ok, thank you.
