### ISSUE TITLE
"babylon" cannot be recognized as a valid HTML tag

### ISSUE THREAD

**Issue by 13120123180** [BabylonJS/Babylon.js#15530]
When I used '@ babylonjs/viewer' in VueJs,
According to the document description, I need to create a "babylon" tag, and my code looks like this:
`<template>`
`  <babylon extends="minimal" model=" https://playground.babylonjs.com/scenes/Rabbit.babylon "></babylon>`
`</template>`
`<script setup lang="ts">`
`  import * as BabylonViewer from '@babylonjs/viewer';`
`  import {onMounted} from 'vue';`
`  onMounted(() => {`
`      BabylonViewer.viewerManager.getViewerPromiseById("babylon-viewer").then(function (viewer) {`
`          viewer.onEngineInitObservable.add(function () {`
`              viewer.loadModel({`
`                  title: "Helmet",`
`                  subtitle: "BabylonJS",`
`                  thumbnail: "https://www.babylonjs.com/img/favicon/apple-icon-144x144.png",`
`                  url: "https://www.babylonjs.com/Assets/DamagedHelmet/glTF/DamagedHelmet.gltf",`
`              });`
`          });`
`      });`
`  })`
`</script>`

Unfortunately, I received a warning:
`[Vue warn]: Failed to resolve component: babylon`
`If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. `

I have read the source code of the viewer and did not find a declaration for the custom tag 'babylon'. This issue has now prevented me from continuing to write my code.
If there is any way to solve this problem, I suggest you explain it in the official documentation.
Thank you, good luck to you.

**Comment by RaananW** [comment]
As the issue template states, we use issues to track our progress and track validated bugs. We ask devs to join our forum and ask the question there so we can get some examples and information answered before we define anything as a bug.

I would appreciate if you asked the question there, and also provided a project we can debug (instead of just a code snippet).

To answer you direct question, this feels like a vite issue not accepting custom tags, which HTML5 does accept. A quick search would have found this - https://github.com/vitejs/vite/issues/153, which is probably what you need to do.

Closing this issue, will answer in the forum if you have any further questions.
