### ISSUE TITLE
Add support for webgl2 occlusion queries

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#1819]

**Comment by clementlevasseur** [comment]
Hey @deltakosh,

With @Breush, we'd like to work on this subject ! Is it ok for you ?

**Comment by deltakosh** [comment]
obviously it is ok:)
let's just discuss here about how you want to implement it(or perhaps using a PR? you decide:))

**Comment by clementlevasseur** [comment]
We want to create a POC before making a final PR !
I'll tell you when we have a something !

**Comment by deltakosh** [comment]
Sounds perfect

**Comment by IbraheemOsama** [comment]
@deltakosh I'll start working on this, I created a POC to test how the occlusion query works, simply I have a cube and a rectangle, the cube is rotating behind the rectangle if part of the cube is visible to the viewport then I change the color of the rectangle and if the cube is not visible in the viewport reset the rectangle color.
Here is the Poc in case you want to have a look.
http://occlusionquerypoc.azurewebsites.net/

Here is how I see it could be implemented in BabylonJs. we add 2 optional properties or add a function or constructor overload in any drawable object

1) OcclusionType an enum that has 2 values strict and optimistic
2) OcclusionRetriesNumber default is -1

here is the logic.

Before we draw any drawable we check if occlusion query is requested on this drawable 
if not {draw this object}
if yes {

Create a transparent bounding box for this object and draw the bounding box.
query the bounding box if it is available or not 
if available check result and draw or not based on the result
if the query is not available do nothing in the current draw method and just check if the query is available in the upcoming draw methods and increment the internal variable occlusionRetriesNumber and once available then draw or not.

here comes the OcclusionType and OcclusionRetriesNumber to be used in case the query took long time if object internal variable occlusionRetriesNumber is equal to OcclusionRetriesNumber then break
in case of break
if the occlusionType is strict then don't draw the object and if optimistic then draw the object.
if OcclusionRetriesNumber equals to -1 then wait for the query and never break.
I’ve a question does OcclusionType required? from my point of view yes but I wanted to check with you.
This is how I see it :) I'll fork the repo to get my head around how objects are drawn in the library.

This implementation would do some flickering if the user moved the camera in a very fast way because an object should be rendered in the current frame but we would wait for the next one because of the query. but this implementation is much better than waiting and block the requestAnimationFrame until the query result is back.

what do you think, should I start implementing this way ?

**Comment by IbraheemOsama** [comment]
From my investigation, objects with occlusion query need to be rendered after all others because the query always return that the objects are visible if objects with occlusion query is rendered before the blocking objects.

**Comment by deltakosh** [comment]
This sounds extremely positive!
I'm perfectly aligned with your logic (Just adding that if webgl2 is not supported then nothing happen at all and mesh is just drawn)

I see this as two properties (occlusionType and occlusionRetryCount) for meshes only for now. (the two you mentioned are fine, just do not use TS enums but plain integer (like what I did for Texture.LINEAR_NEAREST_MIPNEAREST for instance): we don't want to test against strings during frame rendering)

Regarding rendering them after all objects: I see this as a blocker because we need to render transparents objects after all other objects (because of transparency :)). So this is the only remaining point we need to validate: can we render all opaque then all occlusion based then all transparents?

**Comment by IbraheemOsama** [comment]
Will validate it then start in implementing :)

**Comment by deltakosh** [comment]
You rock
