### ISSUE TITLE
Caching strategy affects layout when design size is set

### ISSUE THREAD

**Issue by TMTHY** [BabylonJS/Babylon.js#1867]
Here is PG
http://babylonjs-playground.com/#AWMMA#1

Uncomment  "cachingStrategy: BABYLON.Canvas2D.CACHESTRATEGY_TOPLEVELGROUPS"
to see primitives' layout changes.

That bug make caching unusable with design size;

**Comment by nockawa** [comment]
DesignSize.... I never planed this feature upfront and when @wyklion came up with it I couldn't refuse to implement it, but it's the kind of features that need to be planned from the start... I look on this right now

**Comment by wyklion** [comment]
Nice. some one find bug before me. Make you things to do. lol

**Comment by nockawa** [comment]
I don't know what @TMTHY is working on, but yes, he tests a lots of things! lol

**Comment by nockawa** [comment]
By the way, next week I'll work on finalizing my integration test framework, I'll have a web page with four HTMLCanvas element, running each integration test with different caching strategy and different settings like DesignSize (if 6 is needed instead of 4, it will be 6), so I can run all my tests one after the other but with different combinations to make sure it works in different contexts
