### ISSUE TITLE
Optimize isReady and bind for materials

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#1961]
- [x] isReady for StandardMaterial
- [x] isReady for PBRMaterial
- [x] isReady for Material library
- [x] optimize bind cache for matrices
- [x] reword documentation about CheckOnlyOnce and material.freeze

**Comment by BitOfGold** [comment]
I don't really know this error is conected to this, or shadows, because it happens with every type of shadow, with PBR and standard materials.
Just turn on a pointlight, with any other light with a shadow generator.
Shader error shows up in console, and swithches of shadows.
I hope i posted this the right place :)

[http://www.babylonjs-playground.com/#1HTDCZ](http://www.babylonjs-playground.com/#1HTDCZ)

BTW, thanks for your work with isReady, it is one very important performance thing.
No need for cacheing and freezing materials anymore?

**Comment by deltakosh** [comment]
this is the good place for that. I'll check it asap:)
regarding caching or freezing it should be unnecessary as soon as I would have fixed everything:)

**Comment by deltakosh** [comment]
Should be good:)

**Comment by BitOfGold** [comment]
It works, thanks!!!

**Comment by BitOfGold** [comment]
I have some error messages after compiling custom babylon version.
It has "PushMaterial" in it so I think this the right place again :)
/Tools/Gulp/custom.config.js is now the unchanged version from the master.

![custom_errors](https://cloud.githubusercontent.com/assets/7027091/24675660/56732084-1980-11e7-9acc-aeebc66196be.jpg)
![pushmaterial](https://cloud.githubusercontent.com/assets/7027091/24675668/5a3b9840-1980-11e7-912c-2aa7b43cbb38.jpg)

**Comment by deltakosh** [comment]
can you publish a page using your custom build? It's gonna be easier to debug :)

**Comment by deltakosh** [comment]
Nevermind I found the problem :) can you get the latest customconfig.json?

**Comment by BitOfGold** [comment]
Thanks, downloaded it and now works perfectly!
Thanks!
