### ISSUE TITLE
Canvas2D Precision for decimals

### ISSUE THREAD

**Issue by mohamedmansour** [BabylonJS/Babylon.js#2113]
Canvas2D does not respect decimals when doing the positioning. Within the code, there are a couple of `Math.round` which removes decimals all together.

In our project, we normalized everything to 1x1x1 to make the math easier. Is there a reason why decimals are not supported for leftPixel, rightRixel, topPixel, bottomPixel? Our panel is 1 unit by 0.6 units.

```
            var panel = new BABYLON.Rectangle2D({ 
                parent: this._canvas, id: "panel",
                x: 0, y: 0, width: 1, height: 0.6, 
                fill: BABYLON.Canvas2D.GetSolidColorBrushFromHex("#00000080") 
            });

            var content = new BABYLON.Rectangle2D({
                parent: panel, id: "content",
                origin: BABYLON.Vector2.Zero(),
                fill: BABYLON.Canvas2D.GetSolidColorBrush(BABYLON.Color3.Purple().toColor4())
            })
            content.marginAlignment.setHorizontal('stretch');
            content.marginAlignment.setVertical('stretch');
            content.margin.leftPixels = 0;
            content.margin.rightPixels = 0;
            content.margin.topPixels = 0.1;
            content.margin.bottomPixels = 0.1;
```

In the Canvas2D Source this is what happened:
```

        PrimitiveThickness.prototype._setPixels = function (value, index, emitChanged) {
            // Round the value because, well, it's the thing to do! Otherwise we'll have sub-pixel stuff, and the no change comparison just below will almost never work for PrimitiveThickness values inside a hierarchy of Primitives
            value = Math.round(value);
            if (this._isType(index, PrimitiveThickness.Pixel) && this._pixels[index] === value) {
                return;
            }
            this._setType(index, PrimitiveThickness.Pixel);
            this._pixels[index] = value;
            if (emitChanged) {
                this.onChangeCallback();
            }
        };
```

I commented out the code where it did a `Math.round(value)`, and it seems working, I don't understand the sub-pixel stuff comment.

**Comment by deltakosh** [comment]
Ping @nockawa

**Comment by mohamedmansour** [comment]
I changed our canvas to `ScreenSpaceCanvas2D` instead of `WorldSpaceCanvas2D` because we normalize our models, but we loose the scaling that comes with worldspace and now harder to work on the computations. So for this bug, for WorldSpaceCanvas, would be best not to `Math.round`

**Comment by nockawa** [comment]
@mohamedmansour sorry for the late reply, busy time for me.
I have removed all Math.round/floor in the code to enable what you're willing to do.
Unfortunately, I'm struggling with Pixel Alignment, Text rendering and Sprite rendering when doing so.
That's why the code is not committed yet.
I don't have much time to work on it, but this is where I spend all my free time on .

About the comment, well, the thing is in WorldSpace you don't care about about Screen Pixel alignment, but you do in Screen Space: if you have a Rectangle2D with only border of 1 pixel, you want it to be aligned with the screen pixel, otherwise you'll get a render that span two pixels with a blurry color.

That's all the challenge: enable AlignToPixel in Screen Space, and don't use it in World Space to allow smaller units.

Btw, with WorldSpace Canvas you can use `unitScaleFactor` to have a WorldSpaceCanvas defined with a higher resolution

_unitScaleFactor: if specified the created canvas will be with a width of size.width*unitScaleFactor and a height of size.height.unitScaleFactor. If not specified, the unit of 1 is used. You can use this setting when you're dealing with a 3D world with small coordinates and you need a Canvas having bigger coordinates (typically to display text with better quality)._

**Comment by deltakosh** [comment]
Moved to Extensions
