### ISSUE TITLE
Define npm/yarn install as primary method

### ISSUE THREAD

**Issue by nicodmf** [BabylonJS/Babylon.js#2261]
As standardisation is the better choice, i prpose to defined npm installation as the first installation choice.

**Comment by deltakosh** [comment]
What does that imply?

**Comment by jmitchell89** [comment]
I think he means using: `npm install babylonjs` or `yarn add babylonjs` in the install instructions over downloading the js and including them with script tags..

As someone who is just starting out it didn't take me long to find the npm package though..

**Comment by deltakosh** [comment]
Makes sense. Do you want to submit a PR?

**Comment by M-Anwar** [comment]
It seems like currently the NPM package for Babylonjs is outdated and is using an older version of the package.json. Requiring babylon through ``var BABYLON = require('babylonjs');`` throws an error ``Cannot find module 'babylonjs'``.

This has been fixed in this commit https://github.com/BabylonJS/Babylon.js/commit/17d2072f9806e9dd88f017d01f4e389449efe602. 
Where ``"main": "babylon.max.js",`` has been correctly replaced by `` "main": "dist/preview release/babylon.max.js",``, which refers to the correct main file.

When will these changes be reflected in the npm module?

**Comment by deltakosh** [comment]
should be good now :) (3.0.4-beta)
