### ISSUE TITLE
DDS packing tool for env texture

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2502]

**Comment by deltakosh** [comment]
Bumping it to 3.2 as env texture size is concerning

**Comment by TrevorDev** [comment]
Any more details on what is needed for this?

**Comment by deltakosh** [comment]
Let's discuss offline

**Comment by sebavan** [comment]
Expecting to have v1 the 26th and fully stabilized one week after.

**Comment by sebavan** [comment]
The stabilization phase and tests have been pretty conclusive :-) and this is currently under implementation here : https://github.com/BabylonJS/Babylon.js/compare/master...sebavan:Env?expand=1

The issue we are addressing is the size and quality of our IBL Environment Textures. We decided to implement our custom packing to simplify sharing and downloading those assets. This file needs to work cross paltform for an easy deployment hence why we are not relying directly on compressed textures.

We are instead packing in one file similar to DDS or KTX containing a json manifest header, the polynomial infromation and all the faces of the mip maps chain from the prefiltered cube texture in .png format (which compresses more than decently and decode really fast in all browsers.).

In order to keep an HDR support with png, we chose to rely on RGBD as it offers a better distribution of the value in the low range than RGBM by keeping the [0-1] range untouched knowing it is generally used more frequently. It is also less complex to decode at runtime than LogLUV when needed. It seems the like the best tradeoff for us.

RGBD also offers none to low transparency in the lower range preventing browser relying on premultiplication of alpha to loose data in the most visible area.

In Webgl2 browsers, we are unpacking the data to HalfFloat or FullFloat texture if supported to speedup the runtime and allow correct some interpolations.

As rendering to LOD or even copy to LOD of Half/Fulll float texture does not work consistently on Webgl 1 based browser, we are unpacking in live the data in the fragment shader. As RGBD interpolation is not correct we ensured with different test cases that the generated visual artifacts were worth the transport gain. It looks ok in the sets of textures we have been testing.

We also introduced a special offset from the max range ensuring that we are not reaching problematic values of alpha in legacy browsers (when alpha is too close from 0 the color quantization is created unacceptable banding artifacts).

The file is also packing the polynomials harmonics vs sphericals to match what Babylon is expected internally speeding up load time by not having to compute or transform them anymore.

We are currently in the latest steps of writing the documentation and identifying our limitations before merging in the repo.

As an example of result, we can now rely on 512px cube sized texture with around 3Mb of data vs 32 Mb for the unpacked version without noticing any blocking quality drops. This also speed ups our time to first frame by not requiring the compute of the polynomials anymore.

Some tooling have been added to the inspector in order to address the packing and also swap of environments.

This will be available on Monday including the documentation :-)

Still pending as of today:
- [ ] Consistent Default Lod Scale matching the LYS generation tool
- [ ] Sandbox support
- [ ] Default environment update
- [ ] Library of default environments
- [ ] Documentation 

cc: @MiiBond

**Comment by sebavan** [comment]
Sandbox support : https://github.com/BabylonJS/Babylon.js/pull/4430/files

**Comment by sebavan** [comment]
Documentation: https://github.com/BabylonJS/Documentation/pull/1039

**Comment by sebavan** [comment]
Default Environment:: https://github.com/BabylonJS/Babylon.js/pull/4436

**Comment by Vinc3r** [comment]
Can't wait to see the doc about this new environement thing :)

**Comment by sebavan** [comment]
https://doc.babylonjs.com/how_to/physically_based_rendering#env-map

**Comment by Vinc3r** [comment]
(yep I just see that, thanks!)

By the way, I think it could be useful to add this [comment](https://github.com/BabylonJS/Babylon.js/issues/2502#issuecomment-394058935) above (linked as *underlying tech* in the doc) somewhere in the babylon.com website isn't?

This could lead, why not, to a new section like *Deep into the technics*, or *Seeing the matrix*, or just Resources > Understand the engine. This could be include explanation of how a triangle is sent to the GPU for example, a note about linear workflow, all this technical stuff which can be -very- hard to understand. What do you think?

**Comment by sebavan** [comment]
I added a link to this thread in the doc actually:
![image](https://user-images.githubusercontent.com/16655165/40962943-e420abb0-685b-11e8-8da5-e7638123e9c2.png)

**Comment by sebavan** [comment]
Moving the left over cleanup to a new tasks as the main part has been shipped:
https://github.com/BabylonJS/Babylon.js/issues/4439
