### ISSUE TITLE
Add DOF (using kernel Blur) to default pipeline and create an autonomous DoF postprocess

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2506]

**Comment by TrevorDev** [comment]
From review with Seb:
- [ ] add utility class for dof
- [ ] inherit from BlurPP instead of adding into blur
- [ ] try to get scene instead of this.getEngine().scenes[0].activeCamera;
- [ ] when using uniform near/far use float2 for the params
- [ ] check for 0 when devide by sum of weights, if so set to 0.0001 or something to make it work
- [ ] use mix for linear interp in shader to replace (original * (1.0-coc))+(blurred*coc);
- [ ] note double check the near + (far - near)*depth; might not work on certain types of camera. See shadow shader.
- [ ] doublecheck focallength 50, fstop: 4 1 meter away should be barely any blur
- [ ] validation
    - [ ]     blur
    - [ ]     dof 4 cameras different views with different focus distance, focal in one page (simple scene 3 sphere 1 plane)

**Comment by deltakosh** [comment]
Please add a demo to the feature demos :) (and mention it in the what;s new)
