### ISSUE TITLE
beginAnimation of Dude does not work on latest Safari on iphone 6 / iphone 7

### ISSUE THREAD

**Issue by zhrichard** [BabylonJS/Babylon.js#2618]
Regarding: 

https://www.babylonjs.com/demos/bones/

This demo doesn't work well on latest safari on iphone 6 / iphone 7 (ios 10.3.3), tried latest Chrome on iphone 7, same thing.

Dude object always back to us :-) looks like beginAnimation doesn't work well. 

I followed the sample code from this demo in my project, same issue.

Demo works well on Android devices like Samsung S7 (Chrome), and desktop computer Chrome.

Thanks for any idea.

Richard

**Comment by deltakosh** [comment]
Seems like they introduced another bug in latest ios... You can try with mesh.computeBonesUsingShaders=false

________________________________

**Comment by zhrichard** [comment]
Thanks for quick help.
If I understand correctly, I added 
newMeshes[0].computeBonesUsingShaders=false;
in importMesh callback function

Unfortunately no luck.

Thanks again.

**Comment by deltakosh** [comment]
you have to do it for all meshes

**Comment by zhrichard** [comment]
You are genius! Works now!

Thanks a lot!

**Comment by Palmer-JC** [comment]
I would have rathered post on the forum, but here goes.  I can reproduce
this error on an iPad Air.  Importantly, I am running 10.3.2.  Wanted to
check this before I went to 10.3.3.

What concerns me is I thought it was supposed to fallback automatically for
cpu skinning.  It is for the head mesh, and I see it in little bit of the
console visible in the debug layer.  I am just wonering out, since console
does not scroll, why only the head fell back?

**Comment by deltakosh** [comment]
I agree about the forum. Anyway, I agree it should farm back automatically but with safari nothing is sure

________________________________
