### ISSUE TITLE
Improve inspector

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2649]
- [x] Add sliders
- [x] Better focus management (clicking on a cell should move the focus to it)
- [x] Add color picker
- [x] Console should be scrollable on touch devices
- [x] Missing properties 
- [x] Sandbox app bar seems to hide the bottomof the inspector

**Comment by Palmer-JC** [comment]
I am having iOS issues, not sure if I can wait much longer for this, or just pester myself with a parade of window.alert()'s, some in catches if I am actually generating an exception.

Would attempt just working on this, but I doubt I can do it.

**Comment by deltakosh** [comment]
What kind of IOS issue? Ping @Temechon

**Comment by Palmer-JC** [comment]
Basically, none of my characters appear.  I know the changes to material pre-compiling for 3.1 fail for me, (have not got around to finding out why yet) but my best guess is it is not working at all on iOS.  This scene, [https://palmer-jc.github.io/scenes/blow_me_baby/index.html](https://palmer-jc.github.io/scenes/blow_me_baby/index.html) the butterfly never appears.  This scene is a custom 3.0 build.

Since I cannot really see anything, I do not know what to do.  If it is materials pre-compile related, would prefer to solve both at the same time.

**Comment by deltakosh** [comment]
Ok I let @Temechon chime in :)

**Comment by Palmer-JC** [comment]
Ok, FYI, Have put scene in the shop by switching to full 3.0 version and explicitly loading 3.0 inspector bundle.  I do not run a local server, so I just push up to github.  On iOS,  the Launch click for the button with inspector visible is in the wrong place.  No biggie.

I am seeing 5 messages which do not quite fit. BUT iOS IS scrolling them!  Scolling is not actually a problem.  My lack of battery juice is though.  So will do a charge up and see what extra logs I can add to find problem.
