### ISSUE TITLE
[Suspect] canvas size not restored correctly when switching back and forth to VR

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#3062]
When entering VR and going back to non-VR, the canvas.width seems wrong

**Comment by RaananW** [comment]
Just ran a few tests - http://localhost:1338/Playground/index-local.html#5MV04#43 switches between a free camera to a webvr camera and back again. the canvas size is correct after switching to the freecamera.

The problem is - what happens when you simply detach the webvr camera without setting a new one. Then the canvas size is wrong. Question is - is that a bug or a feature?

**Comment by deltakosh** [comment]
Obviously a feature:)
Let's consider it a no repro so far

Thanks you:)
