### ISSUE TITLE
Add minimal viewer (size related)

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#3073]
Because size matters

**Comment by RaananW** [comment]
The idea:

A few built viewers, one with full UI capabilities, including all of the needes dependencies, and one with the smallest filesize possible, with no unneeded dependencies.

Also - minify all builts automatically.

**Comment by RaananW** [comment]
I ran a few tests. The entire unneeded dependencies (images, handlebars, htmls) are ca. 100kb not-minified. The majority of the viewer.js file i actually Babylon and its modules (loaders, materials, and Babylon itself).

I added a minified version, which is 2.3MB, and optimized everything I could in order to get the smallest size possible without making any breaking changes.  

Using the "minimal" configuration and the minified viewer will have a very short loading time.

**Comment by deltakosh** [comment]
So we can close this issue?

**Comment by RaananW** [comment]
Why, yes please! 😄
