### ISSUE TITLE
GainNode.gain.value is deprecated (removed from chrome on Jan 2018)

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#3372]
Chrome has deprecate all setter calls to *.gain.value of GainNode objects (used in the AudioEngine)

It will stop working on january 2018 (M64) - https://www.chromestatus.com/features/5287995770929152

They recommend using setTargetAtTime() instead, is smoothing is needed.

**Comment by vortice3D** [comment]
Hi RaananW:

As this warning appears using BJS 3.1, what is supposed you must do in order to avoid that warning? It will follow appearing under BJS 3.2?

What is the context the word "smoothing" (Please use setTargetAtTime() instead if smoothing is needed) is used here. That is, what BJS's API is referring? 

Thanks for your time.

**Comment by deltakosh** [comment]
Nothing :) We are not concerned by this warning as we are not using smoothing. The warning will disapear with chrome 64

**Comment by vortice3D** [comment]
Ok **DK**,...
...and thanks for the info.
