### ISSUE TITLE
Add API for enhancing uniform variable feeding

### ISSUE THREAD

**Issue by xuchen-shadow** [BabylonJS/Babylon.js#3432]
- [ ] Uniform - Array member
Currently we have no way to set an individual member of an uniform array like illustrated below in pure WebGL.

// in JavaScript at init time
var someVec2Element0Loc = gl.getUniformLocation(someProgram, "u_someVec2[0]");
var someVec2Element1Loc = gl.getUniformLocation(someProgram, "u_someVec2[1]");
var someVec2Element2Loc = gl.getUniformLocation(someProgram, "u_someVec2[2]");
 
// at render time
gl.uniform2fv(someVec2Element0Loc, [1, 2]); // set element 0
gl.uniform2fv(someVec2Element1Loc, [3, 4]); // set element 1
gl.uniform2fv(someVec2Element2Loc, [5, 6]); // set element 2

It would be cool if we add such support at both Engine level and ShaderMaterial level.

- [x] Uniform - int
It seems that we do not have an API for setting an integer uniform variable. In Engine class, we have setIntArray, setIntArray2, setIntArray3 and setIntArray4 but we do not have simple setInt. It is the same case in ShaderMaterial.

**Comment by deltakosh** [comment]
For point 1: 
- you can already call engine.setArray2(someVec2Element0Loc, [1, 2]);
- Updating a part of an array in the ShaderMaterial does not make sense because the material will overwrite all values on every bind. But you can still use engine to update it manually without relying on the ShaderMaterial (do not call material.setArray and instead do everything with the engine)
Point 2 is done
