### ISSUE TITLE
PBRMaterial - Reflection banding

### ISSUE THREAD

**Issue by thes3m** [BabylonJS/Babylon.js#4156]
Hi,

I have found that reflections on PBR materials have banding issues, looks like the precision is not high enough, however I have tested this with 32bit prefiltered dds, raw hdr and it also appeared. I could not figure out why this is happening so I am posting this here.

Issue is more noticeable with dark materials as shown in example below, where sphere has noticeable banding on the edges:
http://www.babylonjs-playground.com/index.html#UEXC1Z#1

- Expected result:
Expected result would be smooth reflections

- Current result:
Banding appears on reflection

**Comment by sebavan** [comment]
Hello,

This is due to the precision we are using for the default embedded brdf environment texture. We chose a smaller precision as a tradeoff perf/quality and as it works well in most cases aside rough, none reflective, and none "featured" (flat color on a large area) surfaces.
 
If you ever require more precision, I deployed on our CDN a 32 bit version of the same texture with a sample loading code here: http://www.babylonjs-playground.com/index.html#UEXC1Z#2

**Comment by thes3m** [comment]
Thank you for explaining the reason behind it. Using a float BRDF texture helps with banding, however when roughness is 1 a reflection still looks like it is not fully rough. You can see what I am talking about in the example below. Both sphere have same materials, but different BRDF textures, and they do not match. The one with float BRDF texture looks like there is still too much fresnel effect, even though fresnel should be less visible for more rough surfaces.

Example of float vs default BRDF:
http://www.babylonjs-playground.com/#CSF65L

**Comment by thes3m** [comment]
I used your code provided in example before so I assumed that everything is set correct. Thank you again.

**Comment by sebavan** [comment]
Sorry about that, my bad
