### ISSUE TITLE
Importing modules using Rollup.js fails

### ISSUE THREAD

**Issue by kraftwer1** [BabylonJS/Babylon.js#4391]
```
import { Vector3 } from "babylonjs";
```

... while this works fine using Webpack, it fails using [Rollup](https://rollupjs.org/guide/en):

```
src/main.js → public/bundle.js...
[!] Error: 'Vector3' is not exported by node_modules/babylonjs/babylon.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
src/main.js (1:9)
1: import { Vector3 } from "babylonjs";
            ^
```

**How to reproduce**

```
git clone https://github.com/kraftwer1/rollup-starter-app
npm install
npm run build
```

**Comment by RaananW** [comment]
This is because rollup expects the module to be es6, and not umd (commonjs or amd). Babylon doesn't fully support es6 yet, and the js files don't export anything other than a namespace.
Maybe try using this - https://github.com/rollup/rollup-plugin-commonjs

You can follow the es6 progress here - https://github.com/BabylonJS/Babylon.js/issues/3314

**Comment by Seanmclem** [comment]
Still doesn't seem to work with StencilJs
