### ISSUE TITLE
 [Bug] dcene.onPrePointerObservable doesn't trigger POINTERUP or POINTERMOVE events in some cases - repro included

### ISSUE THREAD

**Issue by fmmoret** [BabylonJS/Babylon.js#4395]
# Bugs

Between 3.2.0-rc.4 & 3.2.0, I started seeing the following behavior in my game.

- Bug repro on [playground](https://playground.babylonjs.com/indexStable.html#7XIM4P#1):
- Expected result:
Expect to get scene.onPrePointerObservable events when moving the mouse when the pointer is down.
 events when moving the mouse when the pointer is down.
- Current result:
No pointermove events are triggered while the pointer is down.

---

Separately, but likely related bug (not sure when this one was introduced -- my game doesn't depend on this one's logic):

- Bug repro on (same playground as above) [playground](https://playground.babylonjs.com/indexStable.html#7XIM4P#1):
- Expected Result:
Expect to get a pointer-up event when releasing your button even if you moved your mouse between press and release.
- Current Result:
Pointer-up event doesn't trigger if you move the mouse after your pointer-down event. It only triggers if you press & release in-place.

---
Addenda: mousewheel events still work while the mousebutton is down.

**Comment by deltakosh** [comment]
Hello!
Bug#1: the previous behavior was a bug because if the scene captures the pointer, we do not expect the preObservables to receive it until the scene releases the pointer
Bug#2: Same reason. The down is capture by the scene if no one block it before


If you want to block the scene to capture you have to let it know that your code wants to capture it:
https://playground.babylonjs.com/indexStable.html#7XIM4P#1

If you still want the previous behavior I can add a boolean on the scene like `scene.doNotCapturePointers` or something along this line
