### ISSUE TITLE
Add vertical mode to Slider

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#4471]

**Comment by ssaket** [comment]
Hi @deltakosh, I would like to point out few other issues as well.

- When you increase/decrease the width of the slider keeping "isThumbCircle" as true, the radius of the circle doesn't change. here's the demo- [https://www.babylonjs-playground.com/#U9AC0N#51](url)

- The same thing happens when both the isThumbClamped and isThumbCircle are true; I think here the shape of the background rectangle needs to be changed.
[ https://www.babylonjs-playground.com/#U9AC0N#52](url)

I have started working on this. Let me know if you have any inputs.

**Comment by deltakosh** [comment]
Your help is much appreciated:)
