### ISSUE TITLE
[BUG] GUI2D - onPointerMoveObservable & Up not trigger.

### ISSUE THREAD

**Issue by quocsinh** [BabylonJS/Babylon.js#4482]
Please refer to : https://www.babylonjs-playground.com/#XCPP9Y#543

Hold & Move the mouse on Rectangle, onPointerMoveObservable will not trigger and then release mouse onPointerUpObservable also not trigger.

**Comment by deltakosh** [comment]
Good catch! Definitely a bug
I'll fix it first thing tomorrow morning :)

**Comment by deltakosh** [comment]
Actually it is not a bug
The containers are not pointer blocker by default. This means that the scene can capture the pointer even when the mouse is over them (in order to control the camera)

You can change this behavior with `control.isPointerBlocker = true`:
https://www.babylonjs-playground.com/#XCPP9Y#544

**Comment by quocsinh** [comment]
Thank DK, it working at well. I think you should add this note to the docs. There will be many person fall into this case :)
And of course, I'll fix it some places in my code, ahaha.

**Comment by deltakosh** [comment]
I will for sure:)
