### ISSUE TITLE
TextBlock: positioning issue

### ISSUE THREAD

**Issue by adrientetar** [BabylonJS/Babylon.js#4716]
- Bug repro on playground: https://www.babylonjs-playground.com/#XCPP9Y#570
- Expected result: The text block displays on the top left
- Current result: When setting the width attribute with textHorizontalAlignment set to HORIZONTAL_ALIGNMENT_LEFT or RIGHT, the text block doesn't show up (supposedly pushed out of screen? comment the 'width' line and it shows up properly). Also when setting resizeToFit (uncomment the line), the control shows up center-aligned, discarding the alignment preference.

**Comment by deltakosh** [comment]
Good catch!
I'll fix that asap!

**Comment by deltakosh** [comment]
For the resizeToFit: when turned on, the container will be resize to text size. So alignment does not make sense as the textblock has the size of the text:)
I will dig into the other issue though

**Comment by deltakosh** [comment]
Ok and the first one is not a bug either :)
You define the with to 100 (and as you do not define an unit it assumes percentage so 100 x100 %)

Doc: http://doc.babylonjs.com/how_to/gui#position-and-size

> You can also not define the unit (In this case the default unit will be used): control.width = 0.5 (which is equivalent to control.width = "50%")

So the best fix is probably to force the unit: https://www.babylonjs-playground.com/#XCPP9Y#571

**Comment by adrientetar** [comment]
@deltakosh I see, but then if I change the width in your example to '100px' then the text block appears centered. So in that case it does discard the left alignment, no?

**Comment by adrientetar** [comment]
Actually nevermind, I see text alignment is how the text is displayed inside the text block, not how the text block is aligned w.r.t its parent.

**Comment by deltakosh** [comment]
OK looks good then

**Comment by deltakosh** [comment]
Perhaps if you want, you can tell me if you have ideas to improve the documentation?

**Comment by adrientetar** [comment]
One thing is the api docs don't specify that left takes pixels by default whereas width takes percents by default http://doc.babylonjs.com/api/classes/babylon.gui.textblock#left

**Comment by deltakosh** [comment]
Ok thanks! I will update that info ;)

**Comment by adrientetar** [comment]
Cool! Any chance for a new "alpha" release?

**Comment by deltakosh** [comment]
You mean on npm?

**Comment by adrientetar** [comment]
Yep.

**Comment by deltakosh** [comment]
End of this week :D

**Comment by michael-ts** [comment]
> resizeToFit: when turned on, the container will be resize to text size. So alignment does not make sense as the textblock has the size of the text

So I've read this: https://doc.babylonjs.com/features/featuresDeepDive/gui/gui#position-and-size

And I still don't know how to insert a TextBlock into an AdvancedDynamicTexture and be able to control where it is positioned.  If I set textBlock.leftInPixels = textBlock.topInPixels = 0 I am expecting it to insert the text at the origin, but instead it positions it in the middle when textBlock.resizeToFit=true.   With textBlock.resizeToFit=false, which is the default, it works, but then when I try to read the actual width and height of the text it gives me the width and height of the entire canvas instead, which is why I need to set textBlock.resizeToFit=true. 

> text alignment is how the text is displayed inside the text block, not how the text block is aligned w.r.t its parent.

So how do I align the resized text block with its parent's origin?  It seems to be aligned by default to the parent's center which is not helpful for me.   And since the parent is an AdvancedDynamicTexture I don't know its width either as it does not appear to have a width property so I can't manually subtract off half the width.
