### ISSUE TITLE
GLTF serializer - Animation frames in serialized GLTF are different than in babylon

### ISSUE THREAD

**Issue by VarshaKamble159** [BabylonJS/Babylon.js#4815]
Hi @deltakosh  and @kcoley ,

I am back with another GLTF serializer issue :smile: 

Animations or animation frames are different in Serialized GLTF model. Attaching both the folders for reference.
[ge_model.zip](https://github.com/BabylonJS/Babylon.js/files/2222498/ge_model.zip)
[ge_model_gltf.scnassets.zip](https://github.com/BabylonJS/Babylon.js/files/2222499/ge_model_gltf.scnassets.zip)

Code I am using for serializing is as follows:

```
SERIALIZERS.GLTF2Export.GLTFAsync(this._scene, filename).then((gltf) => {
     console.log('GLTF files',gltf);
});
```
Version of babylon and babylon-serializer is as follows:
```
  "babylonjs": "3.3.0-alpha.11",
        "babylonjs-serializers": "3.3.0-alpha.11",
```
Please suggest me for the same.

Thanks.

Regards,
Varsha

**Comment by VarshaKamble159** [comment]
Hi,

Tried with the latest version of Babylon also
```
  "babylonjs": "3.3.0-alpha.13",
  "babylonjs-serializers": "3.3.0-alpha.13"
```
I am getting following gltf file with above version
[ge_model_gltf.scnassets.zip](https://github.com/BabylonJS/Babylon.js/files/2222882/ge_model_gltf.scnassets.zip)

Thanks.

Regards,
Varsha

**Comment by deltakosh** [comment]
You are a good tester;)

**Comment by kcoley** [comment]
Hey @VarshaKamble159 ! Thanks for flagging and I'll get to this by the end of this week.

**Comment by kcoley** [comment]
Hi @VarshaKamble159, I have forgotten that the animations serialized to glTF are different than the original BabylonJS animations by design to try to minimize file size, export length and deal with Euler rotations (which are not supported in glTF).  
- If the original model has a sequence of key frames with the same value, they would be optimized to a linear animation with the start and end key frame values.  
- The exported frames could also "bake" the animation for Euler rotation curves to quaternions, or curves that blend between linear and spline curves.  
- This optimization was due to some models with many key frames taking too long to export, causing the browser to terminate the export process, or making the resulting glTF files very large.

Is there a specific issue occurring with the animations that you are running into?

**Comment by kcoley** [comment]
@VarshaKamble159 thanks for providing the video.  I'll investigate what is going on with the animations.  My initial suspicion is that an animation group is not being used, so the animations are all separated from each other during export, though I will verify.

**Comment by kcoley** [comment]
@VarshaKamble159 I checked your scene and it is currently not using [AnimationGroups](https://doc.babylonjs.com/how_to/group) to group the animations together.  When not used, the glTF serializer treats the animations as separate entities.

However, I was able to set up a playground which can gather all the animations in the scene and group them into a single animation group, and yield a result similar to the video you provided:

http://localhost:1338/Playground/index-local.html#PH4818
(you can replace the url of the model to the path of your BabylonJS file)

Here is the resulting model exported from the playground: 
[ge_model_combined_animations.zip](https://github.com/BabylonJS/Babylon.js/files/2264318/ge_model_combined_animations.zip)

Is this inline with what you are expecting?

**Comment by kcoley** [comment]
@VarshaKamble159 apologies! Here is the proper link: http://playground.babylonjs.com/#PH4818#1

Yes, this should also work the same with .gltf files as well.

No problem!

~Kacey

**Comment by VarshaKamble159** [comment]
Hi @kcoley ,

Thanks for the playground. It worked well for .gLTF as well :smiley: 
Thanks

Regards,
Varsha
