### ISSUE TITLE
Oculus GO - VRHelper Teleport

### ISSUE THREAD

**Issue by pgbladeqcode** [BabylonJS/Babylon.js#4891]
I tryed a few Demos and own code with the "VRHelper" with my Oculus Go. I figured out that the teleportation function does not work. Does anybody has the same issues ?

**Comment by pgbladeqcode** [comment]
Yes, the best example is:
https://www.babylonjs.com/demos/mansion/

But i althoughfigured out a strange behavior with the positioning (maybe the issue for the teleport bug):

Please look at:
https://playground.babylonjs.com/#ANAL65
In Google Chrome with clicking the VR Button the Box will always follow the Sphere. But on my Oculus GO the Box will only follow on times on "create Scene" (the first frame). 
I use the defualt Oculus Go Browser with the Lastest Babylon Build.

**Comment by deltakosh** [comment]
That's a great repro! We will fix that

**Comment by pgbladeqcode** [comment]
No Problem. Will this be fixed in version 3.3 ? - Do you have an estimate when it will be released ?

**Comment by deltakosh** [comment]
Oh yeah for sure!
Probably by end of this week

**Comment by pgbladeqcode** [comment]
Nice ! Thank you :-)

**Comment by TrevorDev** [comment]
Thanks for finding this. The teleportation issue is a bug PR with a fix is here: #4897

As for the box positioning with the sphere, the issue is that internally babylon actually has 3 gazeTrackers for head, left controller and right controller. When you enter vr and there is a controller active, the controller's tracker is used and when no controllers are active the head's tracker is used. To work around this you could try casting rays yourself. See this PG as an example: https://playground.babylonjs.com/#ANAL65#3  Let me know if you still have an issue with this.
