### ISSUE TITLE
babylonjs.com/sandbox broken throwing 404

### ISSUE THREAD

**Issue by kevzettler** [BabylonJS/Babylon.js#525]
![screenshot 2015-05-24 08 19 57](https://cloud.githubusercontent.com/assets/126209/7788405/f6302d12-01ed-11e5-8293-34cd81c1da22.png)

**Comment by deltakosh** [comment]
Hello, I cannot reproduce the issue

**Comment by kevzettler** [comment]
You should be able to repro with the babylon file in this archive
https://www.dropbox.com/s/sibbpvimq1d53vj/Archive.zip?dl=0

**Comment by davrous** [comment]
Hi!

 I've downloaded your repro and it doesn't load because your .babylon file is referencing some .PSD texture:

 BJS - [15:33:25]: Error while trying to load texture: Bracelet02_03_diffuse.psd
 BJS - [15:33:25]: Error while trying to load texture: Helmet02_02_diffuse.psd

 You need to convert them to .png or .jpg and edit your .babylon file to reflect those changes.

Bye,

David

**Comment by kevzettler** [comment]
@davrous thx
