### ISSUE TITLE
Babylon GUI thorwing error while creating AdvancedDynamicTexture

### ISSUE THREAD

**Issue by VarshaKamble159** [BabylonJS/Babylon.js#5306]
Hi @deltakosh ,

I am trying to import Babylon GUI in project and trying to create AdvancedDynamicTexture. Its throwing me an error.

Following is the code i used for the same

```
import * as BABYLON from 'babylonjs';
import 'babylonjs-materials';
import * as GUI from 'babylonjs-gui';
import * as SERIALIZERS from 'babylonjs-serializers';

var advancedTexture = GUI.AdvancedDynamicTexture.CreateFullscreenUI("UI");

```
Its throwing following error:
![screenshot from 2018-10-05 13-23-11](https://user-images.githubusercontent.com/9550268/46522934-d6924480-c8a1-11e8-8996-f639614127a3.png)

Following are npm versions i am using:
 ```
 "babylonjs": "3.3.0-beta.6",
        "babylonjs-gui": "^3.3.0",
        "babylonjs-materials": "^3.3.0-alpha.1",
        "babylonjs-serializers": "3.3.0-beta.6",
```

Also if I change the sequence of import statements, it throws different errors. What should be the ideal way to import these libs and why that sequence should get followed?

Please suggest for the same.
Thanks.

Regards,
Varsha

**Comment by deltakosh** [comment]
First thing to do it to have all on the 3.3.0 public release. This should solve the issue

**Comment by ssaket** [comment]
Hello All, 

Though in the documentation it says "scene" is an optional parameter which is true but it has to be created before calling this function.

playground link - http://playground.babylonjs.com/#YWDWH9

On analysing I found it is happing because of this line -
https://github.com/BabylonJS/Babylon.js/blob/600cc394caf8c4f6900ad8756b3cc86dd8a72484/src/Materials/Textures/babylon.dynamicTexture.ts#L26

Not sure whether this is a bug or not ! @deltakosh - Can I put a {try} here and get the engine from the static instances method of the Engine class?

**Comment by deltakosh** [comment]
This is not a bug:) you still have to create a scene first and if do not create it even Engine.LastCreatedScene will be empty

**Comment by ssaket** [comment]
Ahh.. I see.
