### ISSUE TITLE
AssetContainer is missing EffectLayers ( HighlightLayer )

### ISSUE THREAD

**Issue by ssaket** [BabylonJS/Babylon.js#5324]
Both addAllToScene() and removeAllFromScene() methods of AssetContainer
doesn't contain effectLayers, because of this the highlightLayer is not added back to the scene.

PG - https://www.babylonjs-playground.com/#5NFRVE#5

Not sure how the GlowLayer is working ! 
Is there any other way to load HighlightLayer ? If not I have a PR ready :)

**Comment by TrevorDev** [comment]
Fixed in pr,
See updated pg: http://playground.babylonjs.com#5NFRVE#11, the reason glow was working was that it was not being added/removed from the scene, asset container already had some logic related to effect layer that seemed to be causing an issue when adding/removing the asset container.

Im not aware of another way to load highlight layer, but maybe @sebavan knows? Feel free to make a PR if you already have something so we can take a look.

**Comment by ssaket** [comment]
@TrevorDev - thanks for resolving this. 
I took a different approach as I didn't know they were part of components. What I did was to add the effectLayers as member of AbstractScene, and loading them like any other (meshes, light etc). But having them in components makes more sense !

**Comment by oschakravarthi** [comment]
Hi, Is it fixed and released?

**Comment by sebavan** [comment]
Yes it is :-)
