### ISSUE TITLE
Error on loading this glb file

### ISSUE THREAD

**Issue by kcoley** [BabylonJS/Babylon.js#5360]
[scene (2).zip](https://github.com/BabylonJS/Babylon.js/files/2474079/scene.2.zip)

Produces this error when loading in Babylon.js sandbox:

Error: "#/animations/0/channels/0/target/node: Failed to find index (undefined)"
![image](https://user-images.githubusercontent.com/3946928/46884990-76ece980-ce0b-11e8-9e56-9f5e76ac7cc4.png)

The glTF validator indicates that the mesh is valid.

**Comment by bghgary** [comment]
The main problem is that the glTF file has animation sampler targets with no `node` property. The loader currently barfs on this. The [spec](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/animation.channel.target.schema.json#L35) does not require `node` to be present, but I don't know what the expected behavior is if it's missing.

@kcoley Can you see why the exporter is generating animation sampler targets with no `node` property?

**Comment by bghgary** [comment]
> expected behavior is if it's missing

Never mind. The spec does say what it should do:

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#animations
> When `node` isn't defined, `channel` should be ignored.
