### ISSUE TITLE
BoundingBoxGizmo causes issues with soft-parented meshes

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#5645]
# Bug

Repro playground: https://www.babylonjs-playground.com/#B92VVX#2

As you can see from the playground, I've got a box mesh with a `BoundingBoxGizmo` attached. Separately, there's an abstract mesh (`mimicRoot`) with another box mesh parented to it. Before every render frame, the transforms (scale, rotation, and position) of the box are copied to `mimicRoot`, causing its child to follow the big box around the screen as it's dragged.

The problem occurs when you scale or rotate using the gizmo. This causes the smaller box to flicker around the screen haphazardly. Eventually, it goes back where it should when you stop dragging.

**Comment by TrevorDev** [comment]
@nbduke does this work https://www.babylonjs-playground.com/#B92VVX#3 The world matrix needs to be updated manually.

**Comment by nbduke** [comment]
That does fix the issue - until you add another layer in between the gizmo and the box. See https://www.babylonjs-playground.com/#B92VVX#4.

**Comment by nbduke** [comment]
Yes, that works. Do you mind explaining why it works? And also, is this a possible performance issue? Is there another way to do it?

**Comment by TrevorDev** [comment]
In Babylon, meshes have a position rotation and scale as well as a world matrix. Creating the matrix from position/roation/scale is a little expensive so babylon tries to do this only once per frame. The bounding box gizmo only modifies the position/rotation/scale but not the matrix but you are trying to get the position rotation and scale of the matrix which may be incorrect as it has not been computed yet. To do this you can call computeWorldMatrix of the parent, because of the way parenting matrix's currently works in babylon the child's matrix also needs to be computed considering the parent's matrix but since the child isn't yet flagged as a dirty matrix it needs to be forced into being computed which is why the true parameter is passed in.

**Comment by nbduke** [comment]
Ok that makes sense, thanks. Would it be better (or equivalent) to call `scene.incrementRenderId()` instead?

**Comment by TrevorDev** [comment]
Yep, that should work as well but instead of just the gizmo object it will do this for all objects in your scene so if you change position/rotation/scale many times after calling scene.incrementRenderId() you may get double matrix computations so I would only recommend doing this to the objects you need if you are extremely worried about perf.

**Comment by TrevorDev** [comment]
Closing for now, feel free to reopen if you hit any issue.
