### ISSUE TITLE
InvalidateRect not working with shadows in firefox

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#5771]
https://forum.babylonjs.com/t/gui-clipchildren-invalidate-rect/730/5

**Comment by TrevorDev** [comment]
Another case where this happens

https://www.babylonjs-playground.com/#7RH606#8

**Comment by deltakosh** [comment]
Unfortunately it turned out to be a bug in firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=1333090

So far we don't have a lot of options:
- You can turn off shadows: https://www.babylonjs-playground.com/#ZU1XRI
- You can turn off clip optimization: https://www.babylonjs-playground.com/#ZU1XRI#1
