### ISSUE TITLE
GLTF Serializing : Lights and Materials properties do not match the scene

### ISSUE THREAD

**Issue by tdurand** [BabylonJS/Babylon.js#5797]
Hello, 

This issue may be related : https://github.com/BabylonJS/Babylon.js/issues/4387 , but I though I will provide my use case so I know more what's going one.

If you export to GLB this playground: https://playground.babylonjs.com/indexStable.html#IFYDRS#26 

![screen shot 2019-01-18 at 18 32 51](https://user-images.githubusercontent.com/533590/51413985-8046ca00-1b4f-11e9-91ec-49f6cfb0a04a.png)

I has two hemi lights that results in no shadows,  and no specular color on the ground material. _(I did it with the stable version of babylon  because the inspector doesn't work with the latest... but the result is the same)_

And you preview the GLB file in VSCode

![screen shot 2019-01-18 at 18 34 05](https://user-images.githubusercontent.com/533590/51414020-b1bf9580-1b4f-11e9-9ae3-6ae3c6569cf2.png)

You see there is some specular effect on the terrain and the colors are not the same, If I open the inspector inside the GLTF preview in VSCode I can adjust some variables to get a better result, like setting the Albedo to white and bring the specular level to 0...

![screen shot 2019-01-18 at 18 36 09](https://user-images.githubusercontent.com/533590/51414156-272b6600-1b50-11e9-948f-85bd0b13fd41.png)

It is something expected while the GLTF serializer isn't finished, or is it a bug ? 

Thanks !

**Comment by kcoley** [comment]
Hi @tdurand .  Currently I am in the process of implementing the KHR_lights_punctual extension in the exporter, so lights will not yet be exportable until it has been merged.  However, hemisphere lights won't be supported for glTF since the specification for KHR_lights_punctual defines them for point, directional and spot lights: https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_lights_punctual

In terms of the parameters, during export to glTF, the exporter tries to do a conversion of the Standard Material to a PBR metallic roughness material.  There will be inconsistencies since Standard Materials are not physically-based materials.  To get a more consistent result when exporting, you can use a PBRMaterial instead.  

Hope this clarifies things

**Comment by tdurand** [comment]
@kcoley , thanks for answering ! This clarifies a lot things 😉. Feel free to close it then, I'll try to work with PBRMaterials. And good to know for the lights !

**Comment by tdurand** [comment]
I'm wondering how to do it with PBRMaterial, here is the playground working (with no light): 

https://playground.babylonjs.com/indexStable.html#IFYDRS#30

```javascript
var groundMaterial = new BABYLON.PBRMaterial("ground", scene);
groundMaterial.albedoTexture = new BABYLON.Texture("textures/ground.jpg", scene);
groundMaterial.unlit = true;
```

Which works nicely in Babylon.js

But when I export the GLB and preview it, I get this, the texture doesn't seem to be applied.

![screen shot 2019-01-21 at 10 35 50](https://user-images.githubusercontent.com/533590/51477810-561c2480-1d68-11e9-8f51-8334e3489548.png)

**Comment by kcoley** [comment]
@tdurand can you try setting the metallic property to 0 and then exporting?
https://playground.babylonjs.com/indexStable.html#IFYDRS#31

If not defined, glTF defaults metallic to 1, but it seems like Babylon defaults to 0.

**Comment by kcoley** [comment]
@tdurand the KHR_lights_punctual extension has been implemented for the serializer.

**Comment by tdurand** [comment]
thanks for the ping ! will have a look ASAP
