### ISSUE TITLE
Position issue with ArcRotateCamera on babylonjs 4

### ISSUE THREAD

**Issue by Gil-1** [BabylonJS/Babylon.js#5951]
Hello,

This is a followup from the forum post here
https://forum.babylonjs.com/t/position-issue-with-arcrotatecamera-on-babylonjs-4/1250

The bug is almost fixed in the last nightly (I was diying for this fix since my post :p)
The same bug occurs with the setTarget function.

Here is the playground to see how it affects the scene 
https://www.babylonjs-playground.com/index.html#3HRWMF#7

So again, to see the bug, just press play and you will see that using setTarget make the bugs coming back.

Let me know if you need anything elses.

**Comment by deltakosh** [comment]
Well this one is not a bug but the expected behavior:

- You set the camera target to box from a camera with no radius (so at 0 targeting the box at 1.5, 1.2, 1.1
- Then you set the camera position to  -1.5, 1.2, -9 while targeting 1.5, 1.2, 1.1. So a new radius is computed to follow these contraints: 10.536
- Then using the current camera position you change the target to 0, 1.2, -1.2 so alpha and beta will be updated but as the radius is set, the camera position will be updated to keep the radius constant ending up with a position set to -3, 1.19, -11
- Then you change the position to -1.5, 1.2, -9, hence the change

**Comment by deltakosh** [comment]
As this is not a defined bug yet we should have this discussion on the forum

**Comment by deltakosh** [comment]
I copy /pasted the discussion back to the forum
