### ISSUE TITLE
Do an alignment check on non ubo uniforms

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#6030]

**Comment by Popov72** [comment]
I used Spector to get the real size of the ubos, to avoid mistakes.

To compute the minimal size, I used:
* vec1/vec2: 2 floats
* vec3: 3 floats if can be followed by a float, else 4 floats
* vec4: 4 floats
* mat4: 16 floats
* float, int, bool: 1 float

| UBO name | Real size (bytes) |  Min size (bytes) | Diff (bytes) | 
|-------------|-----------|-----------|-----|
| Material | 912 | 896 | 16 |
| Scene| 128 | 128 | 0 | 
| Light| see below | see below | 0 | 
| PBR material | 1676 | 1592 | 84 |
| Background material | 204 | 204 | 0 |

For Light ubo, the real size depends on the light type, but in all cases the real size is the minimal size.

Note that the saving for the pbr material (84) is theoretical because the ubo filling is split into multiple calls (for subsurface, sheen, etc) and so can't be optimized globally but only locally in each `PrepareUniformBuffer` methods. In practice, I have been able to achieve a buffer size of 1608, so a saving of 68 bytes. However, it seems the ubo must be a multiple of 16 bytes (according to Spector `bufferLength` values), so all in all the saving is 64 bytes.

So, the savings are 16 bytes for standard material and 64 bytes for PBR material: should I make a PR about this?

**Comment by sebavan** [comment]
not sure it is worth it if it adds complexity at the binding level or lose some logical groups. Thanks for looking into it, closing for now.
