### ISSUE TITLE
glTF Serializer: Some assets export with additional textures

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#6521]
The asset which repros this cannot be shared publicly. If we can figure out what the issue is, maybe we can find/create an asset that can be shared publicly.

The round trip of this asset (load into a sandbox and then exported) causes extra textures to be created and the textures are bigger than the original.

**Comment by Drigax** [comment]
This sounds similar to #6503. Hopefully they are related, but I'll take some time to look at these after I tackle https://github.com/BabylonJS/Exporters/issues/549

**Comment by Drigax** [comment]
Sounds like a mix of a bug, and somewhat expected behavior from my limited investigation.

![image](https://user-images.githubusercontent.com/3952729/60470852-e2374f80-9c16-11e9-9161-75d8d3a69471.png)

I was able to reproduce with an asset (Dude from the meshes library) where the asset has four textures, but exports with five due to materials 35427485 and 51054032 both using texture 3.jpg, which gets duplicated. Definitely a bug.

The increase in texture size was due to the asset being imported with a compressed format (JPG), but the engine does not re-compress as we export the texture from memory, which I'd argue is expected behavior.

**Comment by sebavan** [comment]
Agree for both points, we should only try to prevent the duplicate :-)

**Comment by Drigax** [comment]
https://github.com/BabylonJS/Babylon.js/pull/6567

After more investigation, although we allocate multiple BabylonTextures for texture 3.jpg, they both refer to the same InternalTexture. On export, we modify the name of the texture when clashing before checking to see if we can reuse the GLTFImage, causing the dupe.
