### ISSUE TITLE
Bug with reflections in demo

### ISSUE THREAD

**Issue by Dok11** [BabylonJS/Babylon.js#6574]
https://www.babylonjs-playground.com/ts.html#32H1D4#1
Google Chrome 75.0.3770.100
Win10
GTX 1060 6GB

![image](https://user-images.githubusercontent.com/2697890/60906201-485b4c80-a27f-11e9-819b-6dcc1f826b20.png)

Changing this options provide some repair but not enough
![image](https://user-images.githubusercontent.com/2697890/60906273-70e34680-a27f-11e9-8cb3-8246d0a388e3.png)

![image](https://user-images.githubusercontent.com/2697890/60906375-9f612180-a27f-11e9-9e62-72931c8f4e66.png)

or:
![image](https://user-images.githubusercontent.com/2697890/60906398-b273f180-a27f-11e9-96ef-e415afcb205e.png)

**Comment by sebavan** [comment]
About https://www.babylonjs-playground.com/ts.html#32H1D4#1, it is because the refraction texture is not define so the transparency let you see through the canvas. I addressed this in the fix above.

What you really need for refraction is to set the refraction texture and drop the reflectivity to ensure you can "see through": https://www.babylonjs-playground.com/ts.html#32H1D4#2

**Comment by Dok11** [comment]
@sebavan thank you!
