### ISSUE TITLE
I use window: vrdisplayactivate event to enter VR ,firefox reality browser show loading screen and I can’t do everything

### ISSUE THREAD

**Issue by 298068845** [BabylonJS/Babylon.js#6824]
https://www.babylonjs-playground.com/#SQ5UC1#47
this demo is jump from one playgound to another
https://www.babylonjs-playground.com/#SQ5UC1#49
this demo is jump from one playgound to my project
when i use htc vive and already in VR before,jump from my project to another,firefox browser will show loading screen for long time,i have to quit from VR to break this loading

**Comment by 298068845** [comment]
[log.txt](https://github.com/BabylonJS/Babylon.js/files/3588478/log.txt)

**Comment by RaananW** [comment]
Hi @298068845 ,
Thanks for attaching the error log! Sadly there is no error in the logcat (nothing that concerns the issue here). At least not one I can find.
There are a few issues here:
1. Due to security issues the browsers forces a user to actually enter VR using a user-event. AFAIK there is no way around that, but I am still looking.
2. Another issue is in the playgrounds themselves - even thou chrome is perfectly fine with it, firefox is stricter when it comes to defining variables. Notice that vrHelper is not defined as a local but global variable (no "var" or "let") which can drive firefox ccrazy from time to time).

I am not closing this as I want to be 100% sure what I am saying is right, but I do believe that it is by design and not a bug.

**Comment by RaananW** [comment]
So, did some testing. I sadly dont have a vive, but i do have an oculus rift, quest, and mixed reality.
First for the positive results - in the quest's browser, it is possible to move from one page to another without exiting VR. This is rather self-explained - the quest's entire operating system is a VR OS.
When using a PC and headsets, the situation is different. Edge will throw you out once a new website is loaded. Chrome will do the same. Fierfox, on the other hand, opens steamVR every time i use VR. So when moving to a new website, steamVR is presented and you have to actually click the VR button to load this experiment.

Thou i can"t find any documentation about it, it still seems to me like a security feature. 

BTW - firefox reality browser for the oculus quest has completely crashed a few times, so i couldn't test with it. seems like a browser issue, need to analyse this further. 

I am waiting for your input before closing this, please let me know if I understood it correctly.

**Comment by 298068845** [comment]
I never heard quest，Is it linux system used for pc?
Firefox reality browser for the vive quest has completely crashed a few times too,I think is browser issue,
I try to feedback to firefox company but no respond.

**Comment by RaananW** [comment]
The oculus quest - https://www.oculus.com/quest/
And note that i didn't say `vive quest`, i said `oculus quest`, which is the name of the headset. One can install a firefox browser in that system, and use it to browse the web and watch webvr content. 
I am not sure mozilla can really help with that (apart from finding out why the browser crashed), but as I wrote, this needs to be further analyzed. 
I hope this answers your original question. If it doesn't, please reopen the ticket.

**Comment by 298068845** [comment]
Thank you for your help,I know firefox browser has bug.Oculus quest's browser is ok,Is it mean oculus rift's browser can do this?
