### ISSUE TITLE
Windows MR controller thumbstick doesn't notify updates

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#7217]
# Bugs
Repro playground: https://playground.babylonjs.com/#AM07G2#31

If you connect a Windows MR headset and move the thumbstick, you'll never see the `onThumbstickValuesChangedObservable` fire. The thumbstick state observable and trackpad observables seem fine.

**Comment by brianzinn** [comment]
Need to update playground, so `this.scene` is just `scene`.  Looks like it's here:
https://github.com/BabylonJS/Babylon.js/commit/ce1f9e1be09c608eb590a44e4808ab7ce85b87fa#diff-0f4500018f04962199ec181711d1fb24R623

I'm just downloading the repo to debug on my WinMR headset.  Let me know if I can test changes on my headset.

**Comment by deltakosh** [comment]
@nbduke: Does this one works: https://playground.babylonjs.com/#AM07G2#33

**Comment by deltakosh** [comment]
Closing for now. Please reopen if the fix was not correct

**Comment by nbduke** [comment]
@deltakosh This does not fix the issue.

**Comment by deltakosh** [comment]
Ok reopening..And pinging @RaananW

**Comment by RaananW** [comment]
Will check that. Just wondering - is the thumbstick animating on the model?

**Comment by nbduke** [comment]
Yes the mesh animates.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by RaananW** [comment]
ok, problem found. the value is updated too early, so it is the same as in the cache and is not firing. I can only check in code now since I dont have a device next to me, but the update function must be firing, otherwise the thumbstick would not have animated.

The values of the thumbstick are updated each frame and can be found at `controller.thumbstickValues` . Until I fix it and it is merged (a single line of code if it is the issue I believe it is) you can use those values.

**Comment by nbduke** [comment]
Ok I'll test your change with my headset and let you know if it works.

**Comment by nbduke** [comment]
Yep, can confirm it fixes my issue.

**Comment by RaananW** [comment]
great :-)

**Comment by RaananW** [comment]
reopened until merged, sorry

**Comment by RaananW** [comment]
merged, will soon be available in the playground
