### ISSUE TITLE
Sandbox export to .babylon file breaks animations

### ISSUE THREAD

**Issue by PirateJC** [BabylonJS/Babylon.js#7244]
Forum post with context and example:

https://forum.babylonjs.com/t/about-glb-convert-to-babylon/7324

**Comment by Drigax** [comment]
Thanks for the report, I'm currently working on #5100, since they're related, this shouldn't be too difficult to tackle as well.

**Comment by bghgary** [comment]
First step, investigate the issue.

**Comment by deltakosh** [comment]
Any update @Drigax ?

**Comment by Drigax** [comment]
We have another reported variant via https://github.com/BabylonJS/Babylon.js/issues/7244

I'll follow up on that thread with my findings. In short theres a couple things going on here:

1) we are losing our `Bone._linkedTransformNode` when exporting to .babylon
2) we are losing our `Mesh.skeleton` when exporting to .babylon

which seems to cause our skeletal animations to break on round trip via .babylon

**Comment by tskarthikus** [comment]
I am using a glb with animation and trying to export it as such without any alteration.

![image](https://user-images.githubusercontent.com/1388695/134299453-b35a0964-e9ee-4f05-b4ed-db72546ca770.png)

But, the export is having deformations on bones.
It is reprocible in Babylon Sandbox.

![image](https://user-images.githubusercontent.com/1388695/134299549-5843fdf6-a7be-4c6a-9c7c-a11af711cebd.png)

I think this issue is open.
