### ISSUE TITLE
Oculus controller models don't load in XR

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#7291]
# Bugs
Repro playground: https://playground.babylonjs.com/#AM07G2#42

I tested with an Oculus Quest headset. When you enter XR (by clicking the GUI in the scene), you'll notice that the models for the controllers disappear, and inputs such as teleporting are broken.

Additionally, the `gamepadController` on the `WebXRController` object is undefined.

**Comment by RaananW** [comment]
Thanks @nbduke !

The model loader should use the profiles definition located here - https://github.com/immersive-web/webxr-input-profiles/tree/master/packages/registry/profiles . 

Will take care of this

**Comment by RaananW** [comment]
Will be closed after #7361 is merged.

There is now support for oculus rift and quest (and also vive etc'). The API has changed, please let me know if anything is missing!

Note that there is currently no way of differentiating between the two (they use the same profile "oculus-touch"). If used in the oculus quest directly I use ua-sniffing (yippy) to support the newer quest controllers, but on a desktop it will (At the moment) always use the old oculus touch controllers.

**Comment by mlviz** [comment]
Hi @RaananW ,

I recently switched from WebVR to WebXR (v4.2.0-alpha.16) with an Oculus Quest and I see some small white controllers instead of the Oculus Quest Touch Controller.

Things seem to work  in the babylonjs example on the web, but not on my npm project. Do I now have to include/load the controller assets somewhere? 

(Note: used to work fine on previous version of Babylon with WebVR last January).

**Comment by RaananW** [comment]
The moron controller manager should actually be included in your project automatically, this is why you get the generic controller. You can always load the oculus model directly (webXROculusTouchMotionController.ts) but the profiled moron controller should be working out of the box. Did you turn off the online repository?

**Comment by mlviz** [comment]
Assuming you were talking about the motion controller manager... 
Actually my problem was not directly with the motion controller manager but was similar to https://forum.babylonjs.com/t/web-xr-experience-not-working-in-babylon-4-1/9415, so more to do with the fact that there is a dependency with the babylonjs-loaders.
I simply had to add:
`import 'babylonjs-loaders';`
to my main typescript file to solve it. 
(I didn't have any loader before since I create my meshes procedurally in glsl).
