### ISSUE TITLE
if the model is compressed， it does not work in IE11 browser

### ISSUE THREAD

**Issue by atmjs** [BabylonJS/Babylon.js#7987]
# Bugs
- Bug repro on [github pages](https://issuebox.github.io/babylonjs/ie/compressed.html):
- Expected result: [run normal in IE11](https://issuebox.github.io/babylonjs/ie/uncompressed.html)
- Current result: the page with the compressed model does not work in IE11 browser

# descriptions
I had read the [forum](https://forum.babylonjs.com/t/ie11-promise-is-not-defined/9438) , but can not solve the problem。

## links
[model uncompressed](https://issuebox.github.io/babylonjs/ie/uncompressed.html)
[model compressed](https://issuebox.github.io/babylonjs/ie/compressed.html)

### box.glb
a simple model, only has a simple cube model, then exported from blender.

### box.min.glb
the same model with box.glb, just use compression when export.

### compressed.html
render the box.min.glb model

### uncompressed.html
render the box.glb model

**Comment by deltakosh** [comment]
Pinging @bghgary (I guess this is probably related to promise polyfill?)

**Comment by bghgary** [comment]
I don't believe this ever worked. Draco has to be compiled with a flag to enable IE and I've never compiled Draco until I investigated this issue. But even after I do that, there are some issues that I can't resolve easily.

I'm trying to figure out what happened with emsdk/emscripten such it now wants to use Promise in the fallback Draco js, but I'm some trouble.

Here are all the relevant issues:

> https://github.com/google/draco/pull/405

This PR adds a flag you can pass to Draco CMake so that it can build for IE. I don't believe this flag is enabled for the pre-built versions, but I'm not 100% sure.

> https://github.com/google/draco/issues/596

I filed this issue to see if Draco folks can help with this.

**Comment by bghgary** [comment]
https://forum.babylonjs.com/t/ie11-promise-is-not-defined/9438

**Comment by atmjs** [comment]
It helped me a lot！
@bghgary thanks very much！
