### ISSUE TITLE
Stereoscopic cameras render the scene incorrectly

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#8000]
When rendering the scene using a stereoscopic camera (side by side or over-under, the scene renders incorrectly. 

The current behavior:

![image](https://user-images.githubusercontent.com/1381702/78794988-b9699500-79b4-11ea-839a-467ba29a850c.png)

The expected behavior:

![image](https://user-images.githubusercontent.com/1381702/78794917-a060e400-79b4-11ea-8636-854b758bd2cb.png)

**Comment by foxxyz** [comment]
Is it possible this change has broken the interlaced stereoscopic view (`Camera.RIG_MODE_STEREOSCOPIC_INTERLACED`) added in #7425? Looking at [the changes in your commit in `stereoscopicRigMode.ts`](https://github.com/RaananW/Babylon.js/commit/dc0e8161e8ae60560225b921d9dd32ee100bbea2#diff-f0d7018702701331840fd5e79e3da4c1e0c0413425d38485519e974f8dc2a959L7), there are no more checks for `Camera.RIG_MODE_STEREOSCOPIC_INTERLACED` and setting this rig mode now seems to incorrectly add separate viewports and shows identical output to `Camera.RIG_MODE_STEREOSCOPIC_SIDEBYSIDE_PARALLEL`.

Client workaround for vertical interlacing seems to be:
```
camera.setCameraRigMode(Camera.RIG_MODE_STEREOSCOPIC_INTERLACED, { interaxialDistance: 0.0637 })
camera._rigCameras[0]._rigPostProcess = new PassPostProcess(camera.name + '_passthru', 1.0, camera._rigCameras[0])
camera._rigCameras[0].viewport = new Viewport(0, 0, 1, 1)
camera._rigCameras[1]._rigPostProcess = new StereoscopicInterlacePostProcessI(camera.name + '_stereoInterlace', camera._rigCameras, false, true)
camera._rigCameras[1].viewport = new Viewport(0, 0, 1, 1)
```

But this seems like it should be patched back in as a post-processor in [`Camera._setStereoscopicRigMode()`](https://github.com/BabylonJS/Babylon.js/blob/master/src/Cameras/RigModes/stereoscopicRigMode.ts)...

Let me know your thoughts.. Happy to submit a PR if needed. Thanks!

**Comment by RaananW** [comment]
Hi @foxxyz - this is more than possible :-) We just want to be sure that the window ratio pre and post resizing stays correct.

If you want to open a new issue for this, or even submit a PR with a fix - please go right ahead. Make sure to reference this PR (and me if you want me to review it).

**Comment by Hannes3112** [comment]
Hi @RaananW 
The Stereoscopic cameras are still rendering not correct because they are using the toe-in method rather than an Off-Axis projection. This introduces so called vertical disparities which are quite problematic as they are hurting the eyes and scenes becoming difficult to watch:

![vert Disp](https://user-images.githubusercontent.com/83771104/117315706-38672080-ae88-11eb-8f1f-0d47b68b68de.jpg)

The correct method is called Off-Axis projection, which can be achieved via camera matrix manipulation (shifting the virtual sensor on its x-axis) or viewport cropping.

It would also be very nice if the `isStereoscopicSideBySide `property could be set to squeezed mode because almost all stereoscopic displays with SbS or TB input need it in Half (squeezed) mode, like this: 

![SbS-Half](https://user-images.githubusercontent.com/83771104/117318515-c8a66500-ae8a-11eb-9e8a-70125272cd5f.jpg)

I would be very happy to help with the mathematics / logic and with testing (but not with code, I'm not a programmer).

**Comment by Hannes3112** [comment]
Here is a very comprehensive text about the topic:
http://paulbourke.net/stereographics/stereorender/
