### ISSUE TITLE
Finish frame import / export work

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#8387]
Add Option to save a portion of a graph (and an option to import it as well): Almost done, import does not yet restore links

**Comment by Popov72** [comment]
There's a problem with blocks adapting their outputs to the inputs:

The original node material where the frame has been exported is:
![image](https://user-images.githubusercontent.com/4152247/88940979-bdcdfc80-d288-11ea-9dee-5b8cda713490.png)
As you can see, the inputs of "tata" are vector2, so the output is vector2 too.

The exported and reimported frame is:
![image](https://user-images.githubusercontent.com/4152247/88940870-9bd47a00-d288-11ea-9035-b8993f6b89e3.png)
Now, when importing the frame, nothing is connected to the inputs, so the output has no type. The output is connected to a vector2 input but the link is still red because the output has no type.

Would it be possible that those types of blocks set the type of their inputs according to the type of the output, when the output is connected to something and the inputs are not? Or is there another solution to handle this use case?

**Comment by deltakosh** [comment]
Love that idea! 
We still will have to deal with unknown types when we cannot infer the type from output and in this case we just need to make sure the system will work when I connect an input

**Comment by Popov72** [comment]
Hum, it becomes harder in this case:
![image](https://user-images.githubusercontent.com/4152247/88954593-eb23a600-d29a-11ea-9ee3-4e480a8a60dc.png)

All the blocks have auto-detect inputs and outputs.

The **Negate** and **Min** inputs are meant to be *float* but it's not visible in the screenshot...

I wonder if we should save the types of the inputs of the frame in the json file and set them at import time (don't know if it's possible to force by code the type of a "auto-detect" input?)...

Note that connecting an input does work but it does not propagate:
![image](https://user-images.githubusercontent.com/4152247/88957556-4f486900-d29f-11ea-9e5c-4802e0fd4a5b.png)
The **Negate** input and output are ok, but not the ones for **Sign**, **Max**, etc

**Comment by deltakosh** [comment]
I think it is ok to be undefined as long as connection a block on the first input will propagate

**Comment by deltakosh** [comment]
yes!
