### ISSUE TITLE
No sound after Quest resumes in VR mode

### ISSUE THREAD

**Issue by atneik** [BabylonJS/Babylon.js#8535]
- Bug repro on [playground](https://www.babylonjs-playground.com/#F41V6N#43):
- Repro steps on Oculus Quest Browser:
  - Click anywhere in canvas to get the unmute button
  - Unmute and go to VR mode
  - Trigger anywhere to confirm gunshot sound
  - Put Quest on Standby by using the power button (or just take off the headset for a minute.) and then bring it back.
  - Still in VR mode, Trigger anywhere
- Expected result: Sound is played upon Trigger
- Current result: No Sound :(

**Comment by RaananW** [comment]
Investigating whether it is a platform issue or a babylon issue

**Comment by RaananW** [comment]
This seems to be an issue with the oculus browser's audio support. When closing the quest and turning it back on it goes to mute mode. Quitting the session (left controller menu button) will play the sounds again. This happens when using native audio elements as well :

https://www.babylonjs-playground.com/#F41V6N#48
(Note that each "run" call will add a new audio element, so make sure not to run it too many times but reload).

I will check if there is some form of a hack we can offer until (and if) it is fixed

**Comment by thomlucc** [comment]
Closing as it is an Occulus browser issue
