### ISSUE TITLE
Skeleton Viewer Updates

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Babylon.js#8539]
Looking to improve the skeleton viewer: Update the skeleton viewer with the new bone visualizer (where we can see bones size and rotation. Do all the testing you can to make it ubber robust. Integrate into inspector so when we are in debug mode we can move and rotate the bones with the inspector gizmos. Add an option to see bone weight and influences.

- [x] Skeleton Widget
- [x] Inspector Interactions
- [ ] Weight Shader
- [ ] Finalization and Demos

**Comment by Pryme8** [comment]
Time to roll them bones!  ^_^ Ill post updates on here as I have them.

**Comment by Pryme8** [comment]
So am i restricted to just the current constructor of the SkeletonViewer class or can I reorder it as long as all the system features that use it get updated as well?

I basically want to get it set to constructor(iSkeletonViwerOptions, scene) instead.  I just don't know how that fits into backwards compatibility.

**Comment by Popov72** [comment]
I guess it does not fit with backward compatibility :)

You probably need to do something like:
```typescript
export interface ISkeletonViewerOptions {
    ...
}

export class SkeletonViewer {

    constructor(
        /** defines the skeleton to render */
        public skeleton: Skeleton,
        /** defines the mesh attached to the skeleton */
        public mesh: AbstractMesh,
        scene: Scene,
        /** defines a boolean indicating if bones matrices must be forced to update before rendering (true by default)  */
        public autoUpdateBonesMatrices = true,
        /** defines the rendering group id to use with the viewer */
        public renderingGroupId = 1,
        /** defines an optional utility layer to render the helper on */
        public options?: ISkeletonViewerOptions
    ) { ... }
    ...
}
```

**Comment by Pryme8** [comment]
ew, but ok.

**Comment by Pryme8** [comment]
@Popov72 

In a situation like this where the skeleton has a bunch of wonky transforms on it, what do I do to get things to not go crazy once the skeleton is applied?

Skeleton Off Everything is in the right position (and I know I have the correct weights)
https://playground.babylonjs.com/#LS8CPQ#3

Skeleton On everything goes crazy
https://playground.babylonjs.com/#LS8CPQ#4

But in a normal skeleton everything is ok:
https://playground.babylonjs.com/#LS8CPQ#5

**Comment by Pryme8** [comment]
I am scared I am not going to be able to resolve the problem that is referenced here:
https://forum.babylonjs.com/t/return-to-rest-not-behaving-as-expected/12570/15?u=pryme8

If that is the case what is my path to take as far as upgrading this?  Just have a fallback for the lines render?  I could also have an argument for the Viewer not to be a single mesh and just parent each sphere and spur to the specific bone for cases when the weights are making things go crazy; but that would not be ideal as thats a ton of draw calls.

**Comment by Pryme8** [comment]
I've been digging more into the problems with binding the SkeletonViewer to the skeleton where there are odd setups. 

I really think the fact that we are not able to return the skeleton to a T-Pose (even though in blender the same glb can) which I have been trying to get solutions for in the above mentioned thread, is going to be a huge hindrance on my successful deployment of this element.

At this point Im not sure which direction to go other then assuming to keep the line rendering as a fallback for now till this restPose issue gets resolved.  I can start getting the other aspects done for now but I just wanted to be really clear that I am blocked producing a final product for now.

**Comment by deltakosh** [comment]
@Popov72 / @Drigax : Can you guys have a look to help ?

**Comment by Popov72** [comment]
Having a look but can't give a timing...

**Comment by Pryme8** [comment]
I appreciate it dude a whole lot especially sense this is not your expertise.  If you need more data from me let me know, I have a bunch of GLBs we can go over.

**Comment by deltakosh** [comment]
no rush

**Comment by Pryme8** [comment]
https://playground.babylonjs.com/#LS8CPQ#13

Maybe this will help narrow things down.  On this one I commented out lines 415 & 416.  If you uncomment either one the widget flips.

Does this behavior help us home in on the problem at all?  Might be unrelated, but then Im not to sure.

**Comment by Pryme8** [comment]
With the Inspector Interactions, what is the list of tasks you think are associated with this?
- Enabled Widget
- Change View/Render Type (lines, spheres, spheres&spurs)
- Size parameters for the second two view types
- Clicking a bone in the Inspector behaves the same as a transformNode when rotation,transform,scale widgets are enabled regardless if its a linkedTransform bone.

Anything else?

**Comment by deltakosh** [comment]
Nope, that would be great!

**Comment by Pryme8** [comment]
Next milestone I was thinking it might be smarter to just enhance the StandardMaterial to render out the weights and stuff?

Also I need to update the gizmo placement on the bones as it does not seem to like going to the correct spot on skeletons not at origin.

**Comment by deltakosh** [comment]
Im would prefer a custom material (like a simple shadermaterial) so we can replace it like here:
https://github.com/BabylonJS/Babylon.js/blob/master/inspector/src/components/actionTabs/tabs/propertyGrids/meshes/meshPropertyGridComponent.tsx#L168

**Comment by Pryme8** [comment]
Ok!  So don't worry about supporting lighting or anything like that?  Makes my job easier honestly~!

**Comment by deltakosh** [comment]
Nope it is for debugging purposes ':)

**Comment by Pryme8** [comment]
Sounds good, you will have that very quickly then.  CustomShaders are way easier then a StandardMaterial extension!

**Comment by Popov72** [comment]
Why not a node material? That way it may be easier to update it later on.

**Comment by Pryme8** [comment]
I suck at the NME.

**Comment by deltakosh** [comment]
This one should be fairly easy :)

**Comment by deltakosh** [comment]
https://nme.babylonjs.com/#5UAGTY

Pinging @PatrickRyanMS to check how Unity or Maya display the weights when building a skeleton

**Comment by Pryme8** [comment]
Did I just talk myself out of work on accident?

**Comment by Popov72** [comment]
You could try something like that:

https://playground.babylonjs.com/#BCU1XR#1460

![image](https://user-images.githubusercontent.com/4152247/89733924-266f6300-da59-11ea-9159-5f311f5fea7c.png)

For a given bone, if a vertex is influenced by that bone:
* weight 1 => color=red
* weight 0.5 => color=yellow
* weight 0 => color=green

If the vertex is not influenced by the bone, color = blue

**Comment by Pryme8** [comment]
@Popov72 That is exactly what I was planning on doing but with a customShader instead of a customMaterial ^_^.  Perfect mockup thank you.

I was also planning on an entire bone map too where like we generate a smooth gradient 3 Color Gradient from like Orange to Blue to Pink or something and then assign each index a color so you can see all the bone assignments at on the map at once, its not as used of a view but is something that like cinema4d provides so you can see your entire mapping at once.

**Comment by deltakosh** [comment]
@Popov72 Unfortunately this is not supported and if @Pryme8 wants to do it with shaderMaterial this is not a big deal. I don't want to over complicate NME for this specific use case

**Comment by Pryme8** [comment]
actually now looking at it, why don't I do it just like the vertex weight does it like in your example Delta and have the StandardMaterial have a new parameters for displayBoneWeight and boneMap.  That way there is support for instances and all the other good animation stuff on the StandardMaterial.

https://github.com/BabylonJS/Babylon.js/blob/master/inspector/src/components/actionTabs/tabs/propertyGrids/meshes/meshPropertyGridComponent.tsx#L198

If I do a CustomShader then wouldn't it be more appropriate for a Static method that returns a CustomShader and it would be a lot of extra now that I think about it in comparison to just adding a bit to the StandardMaterial and its shader includes.

I can do which ever, but some quick insight to at least the static method thing would be nice?

**Comment by Popov72** [comment]
Those properties are very specific and would not be of much use for a regular user / usage, so I feel they should not be added to the `StandardMaterial`.

You should not create a `CustomMaterial` because we don't want the core library to depend on the material library. So a `ShaderMaterial` is the way to go.

Creating a `ShaderMaterial` that supports skeleton and morph is easy, it's only a couple of includes to add in the shader. The only thing you won't have in a `ShaderMaterial` compared to a `StandardMaterial` is light support, but that's not a problem because in your use case you don't need lights.

**Comment by Pryme8** [comment]
Yeah I have done it before in the past no problem!    I'll get it rolling today.

**Comment by deltakosh** [comment]
Everything that @Popov72 said :)

**Comment by PatrickRyanMS** [comment]
Late to the discussion, but this is how Maya displays skin weights:

![image](https://user-images.githubusercontent.com/31326855/89817207-9b47a900-dafc-11ea-9fd3-d48a9c134b57.png)

The important part of the display is that I can easily see the blend of the weights across the mesh. If there are only a couple of color levels corresponding to weights, it's hard for me to visually understand the deformation. So In this display, there are several color steps that I can control, and I get the benefit of smooth blending between the colors corresponding to the weights on each vertex. In this image the arm is the selected bone, and you can see that the arm does have miniscule influence on the mesh in the chest and in this character in the side of the head (though the blue color is near-0 influence) to help smooth deformation.

I think this is the challenge of displaying skin weights, showing the full range of influence possible on vertices, while accurately representing how smooth a deformation will be. This is very similar to what @Popov72  showed above, but with more transitions to display subtle weight changes. which may need to be resolved in several lerps between colors representing specific break points (like 100, 0.75, 0.5, 0.25, and 0) to accurately show the falloff of the influences. So an influence of 0.53125 would be one-eight of the way in a lerp between the color at 0.5 and the color at 0.75. Hope this makes sense.

**Comment by Pryme8** [comment]
@PatrickRyanMS, yessir I am right on page with you.  I should have a prototype for us to play with by tonight.

**Comment by Pryme8** [comment]
@Popov72 https://playground.babylonjs.com/#35XDRU#1
think you could help me wire this up so the bones work here and the model appears where it should in all white?

Things seem to have changed sense I did the underwater shader where I included the bone animations or Im just not connecting the dots for some reason.

Im pretty sure this setup worked in the past:
https://www.babylonjs-playground.com/#BLNIDI#38

so maybe something has changed, or Im a goober?  Either way could you help me out really quick?

**Comment by deltakosh** [comment]
This is what I'm seeing in your PG:
![image](https://user-images.githubusercontent.com/1306056/89829727-eae3a000-db0f-11ea-9dab-783de4a6674e.png)

**Comment by Pryme8** [comment]
That should be unrelated, see the last two PGs I posted.

**Comment by Pryme8** [comment]
never mind I got it!

**Comment by Pryme8** [comment]
Do we want to eventually render the barycentric lines as well?

**Comment by Popov72** [comment]
Nice!

Note that you don't need:
```javascript
            #include<bonesDeclaration>
            #include<instancesDeclaration>
```
in the fragment shader.

**Comment by Pryme8** [comment]
https://playground.babylonjs.com/#35XDRU#10
Is more what I was thinking, but I'm not sure why there are gaps in the weights?

**Comment by Pryme8** [comment]
> Nice!
> 
> Note that you don't need:
> 
> ```js
> #include<bonesDeclaration>
> #include<instancesDeclaration>
> ```
> 
> in the fragment shader.

was a copy and paste error thanks.

**Comment by Popov72** [comment]
You can't do the computation in the fragment shader because of the automatic interpolation done by the GPU:
* assume first vertex is linked to bone 1, second vertex is linked to bone 15 and 3rd vertex is linked to bone 58
* for eg (depending on the triangle), the GPU is going to interpolate between 1-15 and 1-58, then on the results of both computations

So, in the fragment shader you can end up with values for boneIdx = 45.3, which has no meaning and can't be used in the way we want.

**Comment by Pryme8** [comment]
Then how do we make it smoother without increasing the facet count?

**Comment by Pryme8** [comment]
https://playground.babylonjs.com/#35XDRU#17
And there here is a mock up of the SkeletonMap Shader, I know my logic is off which is why its not all rainbow colored right this second.  But this is at least a good base.

**Comment by Popov72** [comment]
Your colors should be between 0 and 1, not 0 and 255:

https://playground.babylonjs.com/#35XDRU#21

Also, you should not always start with the color of bone 0 (see the `start` boolean in the code above to assign the color the first time the bone is found).

**Comment by Pryme8** [comment]
Whoops I assumed setColor3 brought them down to a 0-1 range.

Why does that not do that?

**Comment by Pryme8** [comment]
So I came up with this colorSet to try to keep the boneMap with higher contrast per bone.
Its two triadicts that alternate between every step, so that should ensure at least some color contrast perbone.
![image](https://user-images.githubusercontent.com/1538857/89922866-829aca00-dbb4-11ea-94c7-793c8a08ab02.png)

**Comment by deltakosh** [comment]
Asking @PatrickRyanMS:)

**Comment by PatrickRyanMS** [comment]
Thanks for the new sample, @Pryme8! I think the transitions in this version look much better. But I am not sure if I am understanding the whole context of what you are showing in this PG. When looking at this in terms of the feature we want to build, however, coloring vertex weights for the whole skeleton at once isn't quite what we are looking for. There is context in the display that shows parts of the mesh that are influenced by the leg, for example, but a user would need to know what color corresponds to a particular joint chain. What happens if the skeleton is not a biped or has a lot of extra attachments? That could likely change the color mapping which would require building context with each new rig.

Ideally, we would select a bone in the inspector and be able to switch to a debug view like we do with materials and see a heat map of weights that the bone influences. From the image below (which was earlier in the thread) you can see that one bone is selected in the skin weights dialog on the right. About half way down the panel you see a color scale that is customizable to the weight of the influence. 

What would be great to see is if your shader can handle a color scale mapping from color A (near 1.0 influence) through color B, C, and D, to color E (near 0 influence) displayed for one bone like the arm. I am not being specific about the color because we may want to either allow users to choose colors that are meaningful or maybe we allow the user to select more than one bone and we may need to have a couple of color palettes so you can see the mixing of weights across the selected bones. I'm not sure if that's the UX we are aiming at, but being able to have the ability to set the colors for the heat map would allow any of these scenarios. Let me know if this makes sense to you, if you have any questions, or if I completely missed something about your latest prototype. Thanks!

![image](https://user-images.githubusercontent.com/31326855/89946432-c4893780-dbd7-11ea-9473-28b07cadb081.png)

**Comment by Pryme8** [comment]
![image](https://user-images.githubusercontent.com/1538857/89947369-3615b580-dbd9-11ea-9362-e2963a23861c.png)
 I provided both

**Comment by Pryme8** [comment]
Do we want to display the barycentric data as well so they can still sill their mesh flow?

I can add that but wont be able to do that till next week when I am back in town.

**Comment by Popov72** [comment]
> coloring vertex weights for the whole skeleton at once isn't quite what we are looking for

I was also wondering the benefit of this representation.

@Pryme8 What usage you forsee for the skeleton map shader?

**Comment by Popov72** [comment]
@PatrickRyanMS Is the monster you are showing in the screenshot a model we can use to test the heat map display?

I would like to know if the better shading you have is simply because the weights are more uniformely dispatched than in our test model or if it is the color scale we are using that is not right.

**Comment by Pryme8** [comment]
They use it in C4D and you can even see the color assignments for that view in Patrick Ryans screenshot.
![image](https://user-images.githubusercontent.com/1538857/89955188-564c7100-dbe7-11ea-9005-e19a1df9a477.png)

It helps you see the interactions between bones and if you have your entire mesh weighted.  Its a really similar to sketchfabs way of displaying weights as well.

![image](https://user-images.githubusercontent.com/1538857/89955368-bc38f880-dbe7-11ea-99d7-5cbbd898466d.png)

**Comment by Pryme8** [comment]
![image](https://user-images.githubusercontent.com/1538857/89957068-5fd7d800-dbeb-11ea-8e18-f20c68e9e41c.png)
The Zero to just over Zero transition could be cleaned up a little, but I figured that will look better when I change it from 4 colors to 5 here.

**Comment by Popov72** [comment]
You should not need to do specific things to get the mesh sorted correctly, as long as you don't set `needAlphaBlending` to `true`...

**Comment by Pryme8** [comment]
Weird, it was seeming like there was some sorting issues with this.
![image](https://user-images.githubusercontent.com/1538857/89957543-88140680-dbec-11ea-97a3-48b0cef9ac53.png)
https://playground.babylonjs.com/#35XDRU#24

**Comment by Pryme8** [comment]
![image](https://user-images.githubusercontent.com/1538857/89957940-90b90c80-dbed-11ea-9c3a-e6c6c0b5db6b.png)
Here is the 5 Color update.

**Comment by Pryme8** [comment]
The sorting stuff seems to be isolated to the YETI model

**Comment by Popov72** [comment]
The problem with the rendering of the Yeti comes from the fact that `transparencyMode` is not handled the same way in PBR and in `ShaderMaterial`, because in the latter case it is set to `null`, meaning it is not used to determine if alpha blending must be used. As the mesh has `hasVertexAlpha` set to `true`, the material is considered to be transparent and must be alpha blended.

The easiest fix is to simply set `shader.transparencyMode = BABYLON.Material.MATERIAL_OPAQUE;` for both shaders.

**Comment by Pryme8** [comment]
<3 Yo da man

**Comment by Pryme8** [comment]
![image](https://user-images.githubusercontent.com/1538857/91647815-19201580-ea14-11ea-9ca3-e41745f93521.png)
![image](https://user-images.githubusercontent.com/1538857/91647817-289f5e80-ea14-11ea-82a2-909fea90a49d.png)
 Update cause there has not been one in a while... sorry about that this will be done this week I hope.
