### ISSUE TITLE
Some image textures appear rotated by default

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#8735]
Repro playground: https://www.babylonjs-playground.com/#MXZNK2#2

In the above playground, I've placed two image textures with all default properties. The textures point to what is essentially the same image. The only different is that I opened the one on the right in Paint and saved it, whereas the one on the left is straight off a phone camera. As you can see, the left one appears rotated by default, whereas the right one has the correct orientation. However, if you download the left image or view it in a browser, it gets rendered the correct way.

This feels like a bug, especially since the left image renders properly outside the Playground.

**Comment by deltakosh** [comment]
woot! Really cool one..let me dig into that ;D

**Comment by deltakosh** [comment]
I'm gonna document the fix here because it is a WTF one :D
So here is what I see in Spector:

- texture1:
![image](https://user-images.githubusercontent.com/1306056/90162544-a5121c00-dd49-11ea-9e01-f4a9ef9de3a2.png)

- texture2:
![image](https://user-images.githubusercontent.com/1306056/90162562-ae9b8400-dd49-11ea-8c68-926b9d14ef69.png)

For some reasons, the loader rotate the second one even thought the texture size is CORRECT! (and we read it from the img file)

**Comment by deltakosh** [comment]
Firefox has no issue:
![image](https://user-images.githubusercontent.com/1306056/90162697-e4406d00-dd49-11ea-8b36-2ee6b11a3722.png)

**Comment by deltakosh** [comment]
Ok I feel this is a Chromium issue

**Comment by nbduke** [comment]
@deltakosh Hmm, my repro Playground still has the issue in my Firefox (version 79.0).

**Comment by deltakosh** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1116060

**Comment by deltakosh** [comment]
Works for me on FF79:
![image](https://user-images.githubusercontent.com/1306056/90163589-261de300-dd4b-11ea-96b4-d762105824cf.png)

**Comment by nbduke** [comment]
Well now I feel crazy because it's working for me.... Lol I need a coffee refill.

**Comment by deltakosh** [comment]
Please vote up the issue on chromium site

**Comment by deltakosh** [comment]
@nbduke apparently the image has orientation 6 in the EXIF  which technically means this image is rotated 90 degs counter clockwise

So I wonder if this is really a bug or not

**Comment by nbduke** [comment]
@deltakosh But why does it render not rotated if you open the image in a browser tab? Or if you download it and open it in an image viewer on your computer.

**Comment by deltakosh** [comment]
because I guess the browser does not respect the EXIF info :)
But out of 4 browsers we have 2 who follows (chrome, opera) and 2 who don't (firefox, safari)

So I would recommend removing that info :)

**Comment by nbduke** [comment]
But my point is even Chrome appears to ignore the EXIF info if you just open the photo in its own tab (i.e. outside of the playground). Why is the behavior different if it's in WebGL vs plain HTML?

**Comment by nbduke** [comment]
Some further context on this issue. This originated with some pics one of our customers took on a phone. They expected them to render the same in Spaces as they did on their phone, but instead they showed up rotated. It feels weird to ask them to strip EXIF data (these aren't photographers and may not even know what that is).

**Comment by deltakosh** [comment]
Well now we know:https://bugs.chromium.org/p/chromium/issues/detail?id=1116060

And there is nothing we can do on our side unfortunately

**Comment by nbduke** [comment]
@deltakosh is there some property we can set on the texture to ignore EXIF? Or is that something you could add?

**Comment by deltakosh** [comment]
unfortunately no, we call texImage2D API and there is no control over image interpretation
(more general details: https://jdhao.github.io/2019/07/31/image_rotation_exif_info/)

I think the best option would be to process the image on the backend

**Comment by nbduke** [comment]
I guess what I don't understand is that if the browser is respecting the EXIF orientation, shouldn't it automatically rotate the raw image so that we see it the right way? That blog you linked me to certainly implies that:
![image](https://user-images.githubusercontent.com/38300641/90176693-35f2f280-dd5e-11ea-8a69-f15560bae8f7.png)

And none of this explains why Chrome is inconsistent between rendering the image in HTML vs. WebGL.

**Comment by deltakosh** [comment]
feel free to comment on the chromium issue. My understanding is that only webgl is supporting it so far

**Comment by Popov72** [comment]
> My understanding is that only webgl is supporting it so far

Or the other way around: webgl does not support it and the html rendering is ok.

As I understand it, the raw data are stored as a rotated image (as said in the link above) and a flag in the exif header does acknowledge that. And when it comes to render this picture on screen, the picture should be "unrotated" so that it appears the way the photograph took the picture: even if he rotated his phone to shoot a landscape (for eg), the landscape when displayed should appear normally and not rotated.

Taken from your pictures above with Spector:
![image](https://user-images.githubusercontent.com/4152247/90181045-213f4a80-ddb0-11ea-9473-83d1518fdad5.png)

Apart from being rotated, there's a problem with the picture: it misses the bottom of the original picture.

When rotated:
![image](https://user-images.githubusercontent.com/4152247/90181245-6bc0c700-ddb0-11ea-9a09-8bc7f1902d74.png)

Compared to the right picture:
![image](https://user-images.githubusercontent.com/4152247/90181282-7d09d380-ddb0-11ea-8984-fb0d7458eb40.png)

You see that the picture is cut in its height for the first picture, which is abnormal, you should at least have all the data, even if rotated (after all, this picture is correctly displayed in HTML, so all the data are in the file). That makes me think there's a problem in WebGL and not in HTML, actually.

**Comment by deltakosh** [comment]
Well this is an excellent point. do you mind raising it in the chrome issue?
