### ISSUE TITLE
Explore texture transcoding tasks distribution

### ISSUE THREAD

**Issue by lexaknyazev** [BabylonJS/Babylon.js#8914]
Transcoding UASTC to other high-quality block-compressed formats like ASTC or BC7 is performed per-block. Each block is 4x4 pixels, 16 bytes.

For a typical 1024x1024 texture with all mip levels, transcoding each level independently may be suboptimal because of different task sizes:
| Pixel Resolution | Block Layout | Block Count |
|:-:|:-:|:-:|
| 1024x1024 | 256x256 | 65536 |
| 512x512 | 128x128 | 16384 |
| 256x256 | 64x64 | 4096 |
| 128x128 | 32x32 | 1024 |
| 64x64 | 16x16 | 256 |
| 32x32 | 8x8 | 64 |
| 16x16 | 4x4 | 16 |
| 8x8 | 2x2 | 4 |
| 4x4 | 1x1 | 1 |
| 2x2 | 1x1 | 1 |
| 1x1 | 1x1 | 1 |

An engine could concatenate and transcode all low-resolution levels at once to use fewer JS-to-WASM calls.

Also, transcoding a large texture (e.g. 4096x4096, 16 MB) could be split into several tasks and uploaded in chunks using `compressedTexSubImage2D` to use less intermediate client memory.

/cc  @Popov72

**Comment by Popov72** [comment]
> An engine could concatenate and transcode all low-resolution levels at once to use fewer JS-to-WASM calls.

Are those roundtrips really count for a substantial % of time when compared to the transcoding itself?

> Also, transcoding a large texture (e.g. 4096x4096, 16 MB) could be split into several tasks and uploaded in chunks using compressedTexSubImage2D to use less intermediate client memory.

This one seems difficult/impossible to handle in the current architecture because that would mean adding the call to `compressedTexSubImage2D` inside ktx2Decoder, which I don't think we want/can do because we can't use the gl context in a worker thread. Note that we also want the decoder to work for WebGPU.

**Comment by lexaknyazev** [comment]
> Are those roundtrips really count for a substantial % of time when compared to the transcoding itself?

I'm more concerned about the pattern of submitting uneven workloads as it could make the execution less predictable. Anyway, all these assumptions should be verified.

> that would mean adding the call to `compressedTexSubImage2D` inside ktx2Decoder

The decoder could emit a completion event, transfer the memory buffer, and let the renderer do the upload. With `SharedArrayBuffer` support this could potentially be even simpler.

**Comment by Popov72** [comment]
> I'm more concerned about the pattern of submitting uneven workloads **as it could make the execution less predictable**

Sorry, I don't understand this one.

> The decoder could emit a completion event, transfer the memory buffer, and let the renderer do the upload. With SharedArrayBuffer support this could potentially be even simpler.

So that would be a "synchronous" process (meaning the ktx2Decoder would not transcode the next chunk before knowing that the current chunk has been handled) if the aim is to lower the memory consumption. Else, if several chunks can be handled in parallel, you will end up consuming the same amount of memory, except subdivided into several buffers. Or we would need to limit the number of buffers we can parallelize...

Maybe that's something we should investigate, it does not seem straightforward to me, I will let @bghgary give his thoughts.

**Comment by bghgary** [comment]
I think collapsing the smaller mips into bigger chunk of work is probably not worth it. The logic required to do this is probably all JS code (buffer manipulation is slow in JS) and that will probably end up being worse than doing them individually. This is just a guess though. It's probably best to measure how much time it takes for the lower mips and then if it doesn't take much time, then just leave it, even if the execution is less predictable.

Breaking apart bigger textures is a completely different story. Doing this will enable big textures to parallelizable to different workers, which should reduce memory usage if we also limit the number of workers. For example, we limit the number of workers (to 4 and can be configured to lower if necessary) when decoding Draco to avoid an explosion in memory usage. In practice, this optimization is good, but I don't know if we should do it now.

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/explore-texture-transcoding-tasks-distribution/52748
