### ISSUE TITLE
Inspector not loading : Cannot read property ‘FIRST’ of undefined

### ISSUE THREAD

**Issue by tdurand** [BabylonJS/Babylon.js#9072]
Hi, 

Here is the forum post discussing this issue: https://forum.babylonjs.com/t/inspector-not-loading-cannot-read-property-first-of-undefined/14598

**Repro**

Consider this simple playground: https://www.babylonjs-playground.com/#MMUFZZ , it works the inspect shows up

Click on download code and open the project locally, the inspector doesn’t load and there is an error in the console.

**Screenshots**
![](https://aws1.discourse-cdn.com/business7/uploads/babylonjs/original/2X/5/58fbac30b9a22bc304766f6df1a84276281f8c1d.png)

**How to solve it**

This is due to the inspector: https://preview.babylonjs.com/inspector/babylon.inspector.bundle.js   depending on the loaders module https://preview.babylonjs.com/loaders/babylonjs.loaders.js

So you need to put the inspector <script> tag below the loaders in order to have it loaded first

**What to do**

- at least change the order of the scripts in the download bundle of the playground
- maybe see if it can be possible to have the inspector load without the loaders dependency .. as I think it was the case previously ?

**Comment by deltakosh** [comment]
Yeah this is a problem we are aware of. I will take care of the download bundle but you are right, we need to make sure the inspector can load

**Comment by RaananW** [comment]
The usage of the GLTF Loader inside the inspector on runtime is those two enums:

`GLTFLoaderAnimationStartMode` and `GLTFLoaderCoordinateSystemMode`

Other types (such as the GLTFLoader class) is used as a type and not a value, so it will not fail at runtime.

One way to solve this would be to move those enums to `const enum` instead, so that their values will be embedded (instead of loaded) on runtime.  The only downside is that Javascript users will not be able to use this enum directly (as all values of this enum will be the actually values). As this will break backwards compatibility - I guess we are not going to do that.

Another solution (and this is actually counting on backwards compatibility) is to only embed the values in the inspector. Instead of the enum (or if the enum is not (yet) defined), use the actualy values. This this:

```javascript
public glTFLoaderDefaults: { [key: string]: any } = {
        "animationStartMode": GLTFLoaderAnimationStartMode.FIRST,
        "capturePerformanceCounters": false,
        "compileMaterials": false,
        "compileShadowGenerators": false,
        "coordinateSystemMode": GLTFLoaderCoordinateSystemMode.AUTO,
        "loggingEnabled": false,
        "transparencyAsCoverage": false,
        "useClipPlane": false,
        "validate": true,
    };
```

will look like this:

```javascript
public glTFLoaderDefaults: { [key: string]: any } = {
        "animationStartMode": 1,
        "capturePerformanceCounters": false,
        "compileMaterials": false,
        "compileShadowGenerators": false,
        "coordinateSystemMode": 0,
        "loggingEnabled": false,
        "transparencyAsCoverage": false,
        "useClipPlane": false,
        "validate": true,
    };
```

or (might be the best variant?)

```javascript
public glTFLoaderDefaults: { [key: string]: any } = {
        "animationStartMode": typeof GLTFLoaderAnimationStartMode !== 'undefined ? GLTFLoaderAnimationStartMode.FIRST : 1,
        "capturePerformanceCounters": false,
        "compileMaterials": false,
        "compileShadowGenerators": false,
        "coordinateSystemMode": typeof GLTFLoaderCoordinateSystemMode!== 'undefined ?GLTFLoaderCoordinateSystemMode.AUTO : 0,
        "loggingEnabled": false,
        "transparencyAsCoverage": false,
        "useClipPlane": false,
        "validate": true,
    };
```
What do you think?

**Comment by deltakosh** [comment]
like the latter!
