### ISSUE TITLE
Reflection node is rendering an .env differently than a .dds IBL

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#9180]
When loading a precomputed cube map as a .dds file, the preview on the node and the lighting in the 3D preview look correct. When loading the same IBL saved as an .env (generated from the previous .dds file) the lighting in the node preview and in the 3D preview look wrong. 

**Repro**
- Create standard PBR-MR node material and connect a reflection node
- Set the cube map option on the node to true and then load the attached .dds and then replace it with the attached .env
- Expected result: The rendering on the reflection node preview and in the 3D preview would be the same since this .env was made from the .dds
- Current result: The lighting looks incorrect for the .env file.

**Screenshots**
This is how the .env renders:
![image](https://user-images.githubusercontent.com/31326855/96054488-940f8500-0e36-11eb-8d17-c046a274a375.png)

This is how the .dds renders: 
![image](https://user-images.githubusercontent.com/31326855/96054506-a12c7400-0e36-11eb-8bdd-b7778f66345c.png)

Attaching the .dds, .env, and sample shader below:
[reflectionTest.zip](https://github.com/BabylonJS/Babylon.js/files/5381385/reflectionTest.zip)

**Comment by Popov72** [comment]
Actually it is the .env which is rendered correctly.

A cube texture can be used for other things than the cube environment, so it is not loaded as a pre-filterered texture. That means that for a .dds texture it is loaded as a regular color-encoded texture, so `gammaSpace` is set to `true`, whereas for the .env texture `gammeSpace` is set to `false` because the system knows that .env files are always used as pre-filtered textures.

I'm reluctant to set `gammaSpace` to `false` for `.dds` files because it could be something else than an environment texture, as explained above...

Maybe we need an additional button like `Load as environment texture`?

**Comment by PatrickRyanMS** [comment]
or a toggle in the parameters to set gamma to true or false and let the user decide what the color space should be but I agree with  you that we should not presume intent of the user by generally saying dds should load as linear.

**Comment by PatrickRyanMS** [comment]
I will say that if the env is the correct rendering in the 3D scene, the preview on the node still looks broken as the soft boxes are not white. We may need to grab the color space from the setting on the node to display correctly? Or is it that the alpha channel is actually rendering as alpha rather than a divisor?

![image](https://user-images.githubusercontent.com/31326855/96060880-91b52700-0e46-11eb-937b-0468601f6d62.png)
