### ISSUE TITLE
FBX Exporter just wont work

### ISSUE THREAD

**Issue by jirojo2** [BabylonJS/Babylon.js#93]
Hi.

Im having a really bad time making the FBX exporter to work...

First it was complaining about the XNA Framework Content Pipeline assemblies, which I fixed installing the Game Studio 4.0 (why? i dont know. I had the .net 4.5 and the xna 4.0 frameworks installed already (windows 8.1))

Then it says crap like: Cannot find content processor "SkinnedModelProcessor".
(If I use /sk and if I don't)

Also, trying to compile it.. there is no .sln file, and the folder OBJ and several source files are still linked in the project when there filers are not in the repo...

Can you help me?
Tanks in advance.

**Comment by gr9** [comment]
I know this is a little old; but I battled with this on my windows server 2012 r2 machine after getting it to work without any problems at all on my win 7 vm.  As alluded above (e.g. the suggestion to check zip integrity, and being able to get it work from svn rather than downloading zip from github) for me it was simply a matter of unzipping the github download using 7zip instead of the built in archive utility that ships with windows.  Asside from that; I built the BabylonExporter.sln project using visual studio community (2015) and used the product built from that.
