### ISSUE TITLE
[NME] Profiling and optimizations

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/Babylon.js#9354]
I put that here to start the discussion. feel free to close it if irrelevant.

When working on my demo I got some issues with shader performances.
I have a quite heavy vertex position computation (with multiple texture sampling). When I also use that position in the fragment shader, I guess the code is replicated in the fragment and instead of having only computation on the VS, it gets also done per Fragment.
My idea is to do a recursive prepass when generating shader with this predicate: if all the inputs of a node only depends on per-vertex attributes, then compute only on VS and store the value in a varying.

second request: a VS and FS profiling tab where I can see the complexity of the generated shader. Basically, I want to know the estimated number of instructions, the number of texture sampling and the number of varying.
This will help find performance bottle necks.

**Comment by Popov72** [comment]
> My idea is to do a recursive prepass when generating shader with this predicate: if all the inputs of a node only depends on per-vertex attributes, then compute only on VS and store the value in a varying.

When doing [this shader](https://github.com/BabylonJS/Babylon.js/pull/9138), at first it did not work because the sampling of `currentScreen` was done in the vertex shader as all inputs could be evaluated in the vertex shader.

In my case I solved the problem by simply updating the code of the `CurrentScreen` block because it's what we really wanted: for post processes, we want the sampling to be done per pixel.

But in other cases, we could want the sampling (or any other operation for that matter) to be done either in the vertex or in the fragment, meaning when the heuristic determines the code can be done in the vertex we should still have the possibility to bypass it and do it in the fragment. But how do we allow the user to choose what to do in this case in the NME?

**Comment by deltakosh** [comment]
> My idea is to do a recursive prepass when generating shader with this predicate: if all the inputs of a node only depends on per-vertex attributes, then compute only on VS and store the value in a varying.

This is already supposed to work like that actually. Unless a node forcefully ask to be in fragment.

@CedricGuillemet: Do you have some examples we can use to fix / improve that idea?

@CedricGuillemet: I like the VS / FS profiling tabs. Please create a separate issue for it. We will define who wants to work on it later. This is pretty easy as we already have all the info to build the final shader

**Comment by PatrickRyanMS** [comment]
@CedricGuillemet I also love the idea of the VS/FS profiling. I think this would be really useful even in the early design of a shader so we can make confident tradeoffs early rather than trying to optimize at the end which could invalidate a bunch of work that would not have been necessary had we known going in that the performance trade-offs were too high.

**Comment by CedricGuillemet** [comment]
It must be something else then for my slow material. I'll do a repro after 4.2 release as it's not that urgent.
Issue for profiler tab : https://github.com/BabylonJS/Babylon.js/issues/9373
Closing this one.
