### ISSUE TITLE
Oimo JS plugin acts weird

### ISSUE THREAD

**Issue by Saathvik-s** [BabylonJS/Babylon.js#9520]
**Repro**
- playground : https://playground.babylonjs.com/#2B84TV#22
- Expected result: https://playground.babylonjs.com/#2B84TV#21

**Additional context**
The OimoJS physics plugin acts very weird. The timestep doesn't affect the objects at all, and the ball in the example spins away for no reason at all. I discussed this on the forum ( https://forum.babylonjs.com/t/what-does-scene-getphysicsengine-settimestep-do/15993/4) and @RaananW suggested that I open an issue.

**Comment by RaananW** [comment]
Hi @Saathvik-s ,

The main issue here is oimo ignoring the timestep, which should be investigated. 

The ball spin is correct - the impulse is triggered from the side of the sphere (and not in its center), and oimo calculates the forces correctly, spinning the sphere on its z axis. Unless I missed something, this is the expected behavior.

**Comment by deltakosh** [comment]
Closing as Oimo is unfortunately no more maintained
