### ISSUE TITLE
When vertex/index data is updated for a mesh, the submeshes of its instances (if any) are not updated accordingly

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#9623]
See https://forum.babylonjs.com/t/applying-vertexdata-to-mesh-used-as-instancedmesh-source/16670/5

**Comment by Popov72** [comment]
Not sure how to tackle that one...

The thread in the forum is using `VertexData.applyToMesh`, but we could update the positions/indices data by other means (mesh.setVerticesData / mesh.setIndices for eg) and the fix should work for all cases.

The easiest way would be to let the user update the instances manually by calling a method to do so. This method is already existing on `InstancedMesh`, it is `_syncSubMeshes()`. It is already public but with a leading underscore, so we would need to remove it. That would let the user take the decision to update the submeshes of the instances or not: only updating the indices on the master mesh and not on the instances could be leggit, even if it's not what the OP of the thread is needing.

The other option is to have the `_syncSubMeshes()` function called automatically on all instances (if any) when the positions/indices are changed, but we must make sure we update all the code paths that do that.

What do you think?

**Comment by breakin** [comment]
@Popov72: Just a side note from me who found this issue. In my situation the real index buffer shrunk so not updating the submeshes on the InstancedMeshes casues a crash. A solution for this problem given my limited understanding would be to have picking getting the sourceMesh subMeshes instead of the InstancedMesh-one (why does it have one anyway?). But this is just random guesses from someone who knows nothing about the design so feel free to ignore of course!

**Comment by sebavan** [comment]
I love @breakin approach if doable @Popov72  ???

**Comment by breakin** [comment]
(also a sidenote: I think updating vertices work actually, this is just related to updating indices as far as I diagnosed it)

**Comment by Popov72** [comment]
Using the master sub meshes for picking instead of the sub meshes of the instance would be a breaking change, as the sub meshes of an instance could be setup differently than the sub meshes of the master (I don't know if it happens in real scenarios, but the sub meshes being different between the instance and its master, it could definitely be). Also, that would not fix the main problem being that the indexStart / indexCount properties of the instance sub meshes having wrong values when updating the master mesh indices.

> (also a sidenote: I think updating vertices work actually, this is just related to updating indices as far as I diagnosed it)

Updating the vertex positions of the master mesh must also be taken into account because a sub mesh is also defined by a vertex start / vertex count in addition to an index start / index count.

**Comment by breakin** [comment]
@Popov72: Hm that all makes sense. I feel ignorant here but given that submeshes on instances are ignored for rendering, why would the user change them? It would only affect picking afaict...

**Comment by sebavan** [comment]
Thinking more about it, why not updating always all children in this case ? if you have instance of cube and you modify it to a sphere would you not expect all the instances to be impacted ?

**Comment by Popov72** [comment]
> if you have instance of cube and you modify it to a sphere would you not expect all the instances to be impacted ?

In this case I think yes, but the change can be not so drastic and you could update the indices/positions on the master mesh and use a subset of those indices/vertices in the sub meshes if you want. I don't know if it's a useful use case, though...

**Comment by sebavan** [comment]
Yup, and in this case we should as well refresh the children cause it could lead to some pretty strange cases and other bugs otherwise.

I think we should update the applyToMesh, setVertices and setIndex to refresh the children for now and see later if we got any other needs later for the unsynced version. At Least, the current bug would be addressed in a consistent way.

Any thoughts ?

**Comment by breakin** [comment]
@Popov72: But for rendering it will always use the submeshes of the sourceMesh I think no matter what. I have a hard time thinking that the code that does instancing will special-handle the instances based on the submeshes (they can't be instances if they have different values)... Remember that for cloned meshes this already updates all submeshes automatically (since they are in the meshes-list in the Geometry). So there they are assumed to be automatically synched...

**Comment by Popov72** [comment]
You're right, I have just recreated the submeshes when the positions/indices are updated, see #9660
