### ISSUE TITLE
Error loading a scene with PS5 controller plugged in

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#9680]
**Repro**
- Plug in your handy PS5 controller
- Navigate to [any playground](https://www.babylonjs-playground.com/#0CSD1T#249)
- Result:  Scene renders blank with errors in console (value of undefined in _checkGamepadStatus)

**Screenshots**
![controller_err_pg](https://user-images.githubusercontent.com/6227906/103319239-ed269800-49e5-11eb-9ad3-2a6700c74860.png)

**Additional context**
@spkopa may be able to provide more context / answer questions since he discovered this issue!

**Comment by sebavan** [comment]
Unfortunately I do not have a PS5 controller to test on but I bet on some of the expected values from the controller APIs not being supported :-(

@deltakosh in our team might be able to check as soon as he is back from vacation (if he was able to put its hands on one ;-) )

**Comment by deltakosh** [comment]
Nope I was not able to get one and I hate Sony for that ;)

**Comment by deltakosh** [comment]
@Exolun: can you investigate and provide a PR?

Pinging @PolygonalSun as he may have been luckier than me

**Comment by PolygonalSun** [comment]
> @Exolun: can you investigate and provide a PR?
> 
> Pinging @PolygonalSun as he may have been luckier than me

My initial thoughts are that the default gamepad browser support may not fully or properly support ps5 controllers yet (I'm not sure if PS5 support is fully supported, outside of the support that Steam now provides).  I can take a look and see what's going on though.

**Comment by PolygonalSun** [comment]
Update:  So the reason that the PS5 controllers aren't working is because the method that's being used to handle reading their inputs is treating it as a PS4 controller.  Normally, this shouldn't be a big issue but the Gamepad API implementation for a PS5 controller is being handled vastly different from how previous iterations were being handled.  For example, all D-Pad inputs are being treated as a single axis, rather than 4 buttons.  Because of this, the number of buttons to query is less than a PS4 so we're getting an array out of bounds error.  To fix this, the DualSense controller will need to have its own entry with a proper mapping.

**Comment by deltakosh** [comment]
Can you do a PR?

**Comment by PolygonalSun** [comment]
Since it doesn't look like there's any official driver support for the DualSense on PC (only what Steam provides).  I don't think that we can officially support it in Babylon.js yet either.  For the time being, I'm adding a check that should handle that error but it may take some time for DualSense support.  As soon as it's more stable, I'll add it in.  Here's my PR with the specific check addressing the issue: https://github.com/BabylonJS/Babylon.js/pull/9736

**Comment by PolygonalSun** [comment]
Since my previously mentioned PR has been merged, I've created an issue to add DualSense support in the future (https://github.com/BabylonJS/Babylon.js/issues/9738) and will be closing this bug as resolved.
