### ISSUE TITLE
WebXR Link Traversal

### ISSUE THREAD

**Issue by gabrieljbaker** [BabylonJS/Babylon.js#9860]
When in VR, I'd like to be able to click on a link to a WebXR experience and transition to that experience without breaking immersion. This is possible now via a feature of the WebXR API: https://github.com/immersive-web/navigation#api-proposal

A-Frame already has this baked into their ["link" component](https://aframe.io/docs/1.1.0/components/link.html) which they describe as follows:

_The link component connects between experiences and allows for traversing between VR web pages. When activated via an event, the link component sends the user to a different page, just like a normal web page redirect. To maintain VR across pages, the following conditions must apply:_

_The destination Web page listens to the window [sessiongranted] event and enters VR. A-Frame experiences behave this way by default._

I believe the Oculus Browser is the only browser that has this feature, but letting our users do this from that browser would be incredibly powerful. @RaananW

**Comment by RaananW** [comment]
@gabrieljbaker - I added preliminary support for the event. Had to change the UI component a bit. The implementation assumes that the default webxr experience is used. If it doesn't you can self-register the event and call the enterAsync in code.

I tested on the oculus quest, switching between the playground and a self-hosted experience. It only worked in one direction, (because of the way the playground works), but I will try to incorporate this in the playground when I get the chance.

When you get the chance, please test it after it is merged to make sure it works in your scenarios as well. I am waiting with closing the ticket until then.

**Comment by arpu** [comment]
anyone know if this comes to MS edge?

**Comment by bruchansky** [comment]
I'm very interested in this functionality but can't find any example code or guide to make it work. Would you be able to help? I would like to open a link from a self-hosted babylonjs page to another one, but without exiting the VR session on the Oculus Quest browser. Thanks!

**Comment by RaananW** [comment]
If you create a second page that has the default xr experience (or the xr ui component) initialized on page load it will work automatically. 
We can discuss that at the forum if that's ok with you
