### ISSUE TITLE
Confirm Spec-Gloss texture encoding

### ISSUE THREAD

**Issue by lexaknyazev** [BabylonJS/Babylon.js#9926]
As per the glTF Spec-Gloss extension spec, `specularGlossinessTexture` contains specular color data and uses sRGB encoding.

The source code suggests that it's treated as containing non-color data and probably sRGB decoding is not applied to it.
https://github.com/BabylonJS/Babylon.js/blob/10cfc6880bd8c4637b7ae29331f48bd2d786af70/loaders/src/glTF/2.0/Extensions/KHR_materials_pbrSpecularGlossiness.ts#L85

/cc @bghgary @Popov72

**Comment by Popov72** [comment]
You're right, here's the PR that fixes the problem: https://github.com/BabylonJS/Babylon.js/pull/9928

Note however that the impact was limited because it's only when using a .ktx2 file that this flag is used, so that RGBA is used instead of a compressed format if ASTC/BC7 is not available when dealing with non color data. But the color encoding itself was/is still ok.

**Comment by bghgary** [comment]
@Popov72 The PR is merged and this is fixed right?

**Comment by Popov72** [comment]
Yes, this has been merged 4 days ago.
