### ISSUE TITLE
WebXRFeatureName.IMAGE_TRACKING "required feature not compatible" With BabylonReactNative

### ISSUE THREAD

**Issue by saidmoya12** [BabylonJS/Babylon.js#9997]
Good night.

I'm trying to implement the feature
**WebXRFeatureName.IMAGE_TRACKING** using the example code from https://github.com/BabylonJS/Babylon.js/pull/9512

```jsx
const options = {
  images: [
    {
      src: 'https://i.pinimg.com/originals/2c/2f/73/2c2f73a2b0a1dac2559a6a5e1a64ed43.jpg',
      estimatedRealWorldWidth: 0.3
    }
]};

...
const imgTracking = fm.enableFeature(WebXRFeatureName.IMAGE_TRACKING, 'latest', options);
```

But throws the following error: 
> required feature not compatible

**Smartphone**
 - Device: Xiaomi Mi 9 Lite
 - OS: Android 10 

How can I check the compatibility list or is it an error with my code?

Thanks for your suggestions

**Comment by deltakosh** [comment]
Hey do you mind posting your question on the forum as stated in the issue template?

**Comment by saidmoya12** [comment]
Thanks, it's a pull request so I'm not sure, but thanks I'll find the correct place to put this issue.

**Comment by brianzinn** [comment]
hi @saidmoya12 - you have created an Issue instead of a PR, so there is no code for us to look at.  Have a look here as it may have some pointers:
https://doc.babylonjs.com/divingDeeper/webXR/webXRFeaturesManager#writing-a-new-feature

My guess is that you have marked an XR feature as "required", while you should instead have marked it as "optional", since that device Xiaomi does not support that feature.  You can also preemptively do a query to ask if a feature is supported on your device.

**Comment by brianzinn** [comment]
Also, @saidmoya12 - if it's not a native feature of XR then don't set the `xrNativeFeatureName`.

**Comment by brianzinn** [comment]
🤦‍♂️ this is a closed issue from March 🤦‍♂️  ... sorry I thought it was new since you created an issue in the other repo.
